### ISSUE TITLE
Volume control lag

### ISSUE THREAD

**Issue by joristt** [bitgapp/eqMac#102]
In 2.1, chaning the volume by holding the volume up/down button on the keyboard works smoothly. However, when pressing one of the volume buttons repeatedly (and quickly), there is some weird lag and my cpu usage spikes from 40% to 150-200% on my dual core (but hyperthreaded) mid-2014 macbook pro.

**Comment by joristt** [comment]
I should also add that both eqMac2 and eqMacHelper do nothing weird (or at least, their cpu usage never goes beyond 2%). However, WindowServer, coreaudiod and kernel_task all suddenly feel the need to claim half of the processor. When I rapidly change the equalizer by moving my mouse up and down quickly in the popover view, WindowServer, coreaudiod and kernel_task do stay calm...

**Comment by romankisil** [comment]
I am not experiencing such issues. Granted I do have quite a beefy MacBook :(

**Comment by jakecoxux** [comment]
Can confirm, also occurs on my 1-year-old MacBook Air mid-2015

**Comment by joristt** [comment]
I noticed that when I disable eqMac 2.1, there _also_ is a huge spike in cpu usage when I rapidly press the volume buttons, so that just appears to be normal behaviour. However, the lag in the volume HUD disappears, so there really does appear to be an issue that is caused by eqMac2. Running macOS 10.12.6 btw, and I use no other audio kernel extensions or something like that.

**Comment by i2mo** [comment]
Same here.

macOS 10.13.1
Retina MacBook Pro, Start 2015 (MacBookPro12,1)

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
