### ISSUE TITLE
Sound is Muted then Put on Full Blast

### ISSUE THREAD

**Issue by MaliceofUnderland** [bitgapp/eqMac#112]
I downloaded this yesterday, and it was working just fine. Now when I use it, my volume keeps automatically turning off then going on full blast.

**Comment by hooph00p** [comment]
+1

I see the same when reconnecting with AirPods, or taking out an earpiece and putting it back in. Absolutely terrifying.

**Comment by afinne** [comment]
Happened to me too, nearly blew my eardrums.

**Comment by lbibass** [comment]
same here. Only happens with bluetooth/wireless headphones.

**Comment by tonygnch** [comment]
Same issue happening to me with AriPods. When take off the airpods and then put it back the sound is at full blast.

**Comment by CarlesCG** [comment]
Same issue with Apple TV
![max_volumen_mute_loop](https://user-images.githubusercontent.com/7206134/37708251-2f14f496-2d06-11e8-9512-4274f0c90106.gif)

**Comment by mrfloppi** [comment]
@nodeful: So what's up with this issue, when will it get fixed? I'd be glad because for now, this is really a dealbreaker for me 👎 Thanks for your good work, keep it up!

**Comment by nodeful** [comment]
@mrfloppi I'm not going to update this repo as I decided to do a complete rewrite of the application with new technologies that I am more experienced with (mainly Swift and JavaScript)
I can't dedicate more time to eqMac2 as I am trying to spend all my time developing the new version. Just sit tight, the new release will be miles better than eqMac2 :) Sorry for any inconveniences and lack of communication

**Comment by nodeful** [comment]
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by hayton** [comment]
This happened on wired headphones also when switching output sound devices. Terrible experience. My ears are hurting right now.

**Comment by scarlettsan** [comment]
Still this bug for Wired headphone for mac, eqMac2. 
Had to be cautious to stop all playing music before switching to eqMac.
Sad to hear that it's no longer under maintenance. 

It's a nice tool tho. It made the music I hear so much better, so I learned to live with it.

**Comment by FrenchFlakito** [comment]
@nodeful I just downloaded the software and I'm currently using it to optimize the sound on a wireless speaker. So far, awesome. Give me a few hours before I donate :)

However, even before experiencing this bug, I feel concerned ^^ I just wanted to make this bug a bigger priority in your list, by putting forth the argument of security. 1) people report pains after the bug occurs 2) just imagine if this happens to someone on a bike or in a car.
I don't know if this is easy to fix, but if it is, I think it is worth a few hours.

Still, very happy so far !

**Comment by chucktdriscoll** [comment]
> @nodeful I just downloaded the software and I'm currently using it to optimize the sound on a wireless speaker. So far, awesome. Give me a few hours before I donate :)
> 
> However, even before experiencing this bug, I feel concerned ^^ I just wanted to make this bug a bigger priority in your list, by putting forth the argument of security. 1) people report pains after the bug occurs 2) just imagine if this happens to someone on a bike or in a car.
> I don't know if this is easy to fix, but if it is, I think it is worth a few hours.
> 
> Still, very happy so far !

This project is now defunct and won't get any fixes as all work that _would_ have gone into eqMac2 is being funneled into its successor.

**Comment by jbbohrer** [comment]
Works fine so far with my BeatsX on Mojave. I was trying to find a solution for Spotify missing an EQ settings like mobile versions.
![screen shot 2018-11-06 at 1 27 28 am](https://user-images.githubusercontent.com/44797098/48046886-087a1d80-e164-11e8-9b03-3d9865cd1497.png)
![screen shot 2018-11-06 at 1 31 31 am](https://user-images.githubusercontent.com/44797098/48046887-087a1d80-e164-11e8-91a8-1dfcc301ed47.png)

**Comment by crstestacc** [comment]
I also use it on Mojave without and problem, 10x man for this nice piece of software.

**Comment by bassages** [comment]
Very bad bug, it happened to me when switching fro 10 to 31 band eq. The volume went to insane loud level. Uninstalled immediately. I rather listen to a bad eq'd sound than becoming deaf.

**Comment by virajkanwade** [comment]
Been a year with no fix and no successor too!

**Comment by brieucdlf** [comment]
Happened to me just now ^^ Well guess the bug will not be fixed anytime soon :( Nice app btw !

**Comment by ajjrice** [comment]
For what it's worth, I think the bug is in [EQHost](https://github.com/nodeful/eqMac2/blob/master/eqMac2/Source/EQHost/EQHost.mm) -- look at the code. If the method `createEQEngineWithOutputDevice` is called it dutifully saves the volume settings and then right at the end of the method is the code `[Devices setOutputVolumeForDeviceID:output to: 1]; //full blast` 

I'm a programming novice and I'm not quite sure how to fix this. It might be as simple as commenting out that line, or changing it to `[Devices setOutputVolumeForDeviceID:output to: stashedVolume];`

**Comment by Glorfindelor** [comment]
> First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
> I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
> I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
> Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :)
> 
> Heres a sneak peak of the UI I am currently working on:
> <img alt="screen shot 2018-05-07 at 20 14 47" width="460" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

Looks so promising! Any news on the project?

**Comment by Moulde** [comment]
I just found this repo looking for some equaliser for osx, and it really looks great!
I just wanted to add my 2 cents, and I am not trying to bash on you or anything, but I kind of like the old flat interface, it looks like an OSX app, which I really really like, and I would prefer all my osx apps to have the same style, instead of going full winamp, where every app is using their own style.

Again, just my 2 cents, and I love your landing page!

**Comment by mrfloppi** [comment]
@nodeful Hey hey it's been 1 and a half year since you told me this bug can't be fixed, because you're working on the v3 right now. Sadly there haven't been any updates on that til today, so it would be very nice to know what's the status here? 🙂 Thanks mate!

**Comment by prpatel78** [comment]
Eagerly awaiting v3!

I found a script online, that allows you to set the max volume level on your mac, as a workaround the random volume at 100% issue, we are all having with eqMac2. Google "limiting your mac's volume in 2019", the script, written by "Lucas Andión" is easy to set up, I have no scripting experience and was able to follow the directions. 

The only issue I have with eqMac2 is the random crashes (I'm running OSX Catalina), but quitting and reopening the app resolves the issue.

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by angristan** [comment]
How to fix this? How to uninstall the kernel extension?

**Comment by SAGARSURI** [comment]
Excited for the newer version. @nodeful

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
