### ISSUE TITLE
Crashes when opening UI after disconnecting audio device

### ISSUE THREAD

**Issue by achimkoh** [bitgapp/eqMac#117]
Hi! I'm really enjoying the software so thanks for that. 

I use speakers connected to my HDMI monitor, so I often switch between built-in output and HDMI. When eqMac2 is set to output to HDMI, then I disconnect the HDMI cable, then try to open the eqMac2 UI (because I want to switch over to built-in output), it crashes. If I open it again it works fine. 

Not sure if this is the case for HDMI output only or for other external audio devices as well. 

macOS Sierra 10.12.6
eqMac Build 2.2

**Comment by levelxplane** [comment]
This happens to me as well, when switching on and off Bluetooth.

macOS Sierra 10.12.6
eqMac Build 2.2

**Comment by okuligowski** [comment]
Same for me.

Sierra 10.13.2
eqMac2 build 2.2

**Comment by lbibass** [comment]
Same for me. High sierra.

**Comment by Nickka** [comment]
Same, 

High sierra 10.13.1
eqmac 2.2

**Comment by aaronmanela** [comment]
Same,
High Sierrra 10.13.2
eqmac 2.2

**Comment by Siraris** [comment]
Same for me!  The only real problem I have with this great app!

Sierra 10.12.6
eqmac 2.2

**Comment by gdbytes** [comment]
Same for me. After changing audio device, typically reconnecting bluetooth headphones, clicking the menu bar icon will crash the app.

**Comment by chattambulo** [comment]
Same problem.

**Comment by Mike-The-Restless** [comment]
Same,
High Sierrra 10.13.2
eqmac 2.2

**Comment by rlopezpe** [comment]
+1

**Comment by capnshupe** [comment]
+1, same behavior experienced when both bluetooth and my usb DAC disconnects.

High Sierra 10.13.3
MacBook Pro (15-inch, 2017)

**Comment by gdbytes** [comment]
Very nice, thanks for your efforts.

**Comment by labnux** [comment]
Keep it up @nodeful. This issue is a little bit painful everyday, but your software is awesome and I'm gonna keep using it. Can't wait for the new version!

**Comment by Nay3ls** [comment]
@nodeful I'm not proficient in Object-C but I don't mind taking a look to see if I can find the problem.  Do you have any idea of witch class/file the bug is in?

I speculate it happens because the connection drops when a macbook goes to sleep and then it reconnects when it wakes up but the reference changes or something.  (I'm just speculating)

Anyhow... I love the fact you made this open source.

**Comment by achimkoh** [comment]
Hi everyone, 

I've found that giving eqMac2 assistive access on my Mac stops the crash. I'm referring to the option here:
System Preferences -> Security & Privacy -> Privacy -> Accessibility -> eqMac2
<img width="780" alt="screenshot of the menu item" src="https://user-images.githubusercontent.com/3594463/40096549-56d5ee76-589f-11e8-981c-5bebb8731b83.png">
Probably concerns #134 and #138 as well.

**Comment by svekl** [comment]
@nodeful thank for all your great work! awesome news about new version, looks stunning, can't wait to touch it, is there any mailing list or something to subscribe to be aware when it comes out?

**Comment by roura356a** [comment]
Same issue here with bluetooth headset after connecting/disconnecting. Still the software is great so I'm still using it.

**Comment by regularlabs** [comment]
Same issue here with (un)plugging HDMI monitor.

Any ETA on the new version?

**Comment by sterlingfire** [comment]
Also having issue with displayport monitor reconnecting after sleep. Any news on the new version?

**Comment by FabianFrank** [comment]
Same issue when unplugging (or waking up from sleep after they were connected, even if they are still connected) USB-A or USB-C speakers.

**Comment by jaybocc2** [comment]
having the same issue after locking/sleeping and resuming.  Using HDMI out and all devices remain connected during sleep and wake.

**Comment by nicolasSchirmer** [comment]
I sent a pull request #161 to try to fix this crash. If any one found a better way to do it please fell free to share it.

## Here is what I've learned:

### The problem: 
When a bluetooth device disconnects from the mac the EQ crashes due to exc_bad_access error. 

### Understanding it:
On the `EQEngine.mm` class, there is a method called `GetEqGains` that checks the current device attached into the EQ through memory addressing retained  by the `mEqualizerUnit1 `object of `EQEngine.h`.

When a device disconnects from the mac, a method is called to wipe the `Devices` from the list of connected devices in the `EQHost.mm` by the `deleteEQEngine` method. But this method leaves residue in the before mentioned `EQEngine.h` class.

### The solution (kind of)
Check if the EQEngine object is null and do not try to set the eq on the ghost audio device.

It would be nice to return to the last device and all... But this was a very fast fix done to help use this wonderful application without the annoying disconnection crash.

**Comment by dmkulazhenko** [comment]
same, @nicolasSchirmer fix works, thx.
Mojave 10.14.4, macbook pro 15" 2017 (MPTT2)

**Comment by ShayMalchi** [comment]
@nicolasSchirmer 
I tried to build your solution, but ended up with a `contents.xcworkspacedata` file I'm not sure how to run. Can you please advise on how to use it?

What I tried (from the original README):
```
git clone <yourFork>
cd eqMac2/
pod install
open eqMac2.xcworkspace
```

@dmkulazhenko maybe you can share how you tested the fix?

Thanks all!

**Comment by robbyking** [comment]
Has anyone resolved this issue in their own fork?

**Comment by ShayMalchi** [comment]
@robbyking I did, but while it wasn't crashing anymore, it didn't work seamlessly and required some extra clicks upon disconnect/reconnect of my BT headphones. Ended up using a different solution called Airfoil (paid software).

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment]
Moving the discussion of this issue to #227
