### ISSUE TITLE
Feature Request: Custom Config Export/Import

### ISSUE THREAD

**Issue by EPICmynamesBG** [bitgapp/eqMac#120]
I'd like to preface, I love the application. I'm recommending it to all my friends. That being said, it would be awesome if there was a way to export EQ profile's I've custom made to share with them. Or even more simply, just to share with myself across devices rather than trying to hand duplicate custom settings each time.

**Comment by nodeful** [comment]
I agree. Will make sure to add this feature in the next big release of eqMac that I'm working on right now. Thanks for suggestion

**Comment by eightygrit** [comment]
In the meantime, this information must be stored somewhere. Can you let us know where on the system you keep the custom profiles stored?

**Comment by nodeful** [comment]
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by eightygrit** [comment]
No need to apologize for how you spend your free time. I appreciate getting to benefit from all your hard work. I know how hard it is to maintain old code while trying to build something new. It sucks. 

The new version looks great. I'd love to beta test when you think it's ready. 🍺

**Comment by roltean** [comment]
Any updates on this? How do we copy presets from one machine to another?
I tried manually copying ~/Library/Preferences/com.bitgapp.eqMac2.plist but it didn't work.

**Comment by anton-iskandiarov** [comment]
+1

**Comment by Juanlvs** [comment]
Hello, Please add parametric EQ filters. I would like to use Room EQ wizard to measure my room (or headphones), match to target with auto EQ and improve the acoustics response. As an advance feature it would be awesome to be able to EQ per channel (or speaker) for each audio device available on the OS app "Audio MIDI Setup".

**Comment by emjimadhu** [comment]
I am looking for this feature where i can export or import my presets. Have it included?

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by qspi** [comment]
> Any updates on this? How do we copy presets from one machine to another?
> I tried manually copying ~/Library/Preferences/com.bitgapp.eqMac2.plist but it didn't work.

Hi guys, I reply this, because I installed the new eqMac and looked for a solution how to reuse my old settings from the old app.

Data structure changed a lot, so what you can do quickly is using math.

In the old plist file the gain numbers are simply mapped from -24..+24 db to -1..+1. Check out my screenshot, color codes for the boxes:
- orange: here is the plist file
- yellow: the plist file
- green: your custom 10 band values

So what you can do is to calc the db manually (24 / gain value) and set it manually in your new eqMac app. 
Btw. the app is still great, no crashes yet, so big thanks for it @nodeful !

**Comment by nodeful** [comment]
The import/export feature is now present in the new eqMac release (small bug with importing see here: #232 )

Regarding transferring old preset to the new eqMac, discussion has moved here: #234
