### ISSUE TITLE
Mac starts at full blast

### ISSUE THREAD

**Issue by btimtsang** [bitgapp/eqMac#123]
On my work desktop, I leave my volume on EQ low at the end of the night before shutting down. Every morning when I start my computer, my mac comes BLARING to life with the infamous "BAHH". It's quite intrusive, not to mention is a great way to let my colleagues know if I've gotten in late...

**Comment by aaronmanela** [comment]
When I start eqmac the volume goes up to full.  I've been restarting because of https://github.com/nodeful/eqMac2/issues/117.
High Sierra 10.13.2
eqmac 2.2

**Comment by scheckley** [comment]
same here, nearly blew my eardrums

**Comment by Overc1ocker** [comment]
This happens to me, but only when switching outputs, then switching back to "built in output"

**Comment by Robula** [comment]
I've just come here to report an issue about this. I have quickly learnt that before I start eqMac2 to remove my in-ear earphones and double check the volume is low (1-3 bars). 

I have noticed that volume will jump to 100% if you switch between audio outputs either through the system or eqMac2, **DO NOT DO THIS WHILST WEARING EARPHONES**.

It would be great to implement some sort of ear-protection system when switching outputs or plugging in earphones into the 3.5mm jack.

**Comment by rails4sandeep** [comment]
Came here to report the same issue. My ears literally blew away due to the sound when i switched on or switched the headphones

**Comment by chattambulo** [comment]
Same problem.

**Comment by gregawoods** [comment]
This has happened to me a couple times. Positively terrifying. 🔊😱🔊

**Comment by danya00** [comment]
switch 10 to 31 band and back  - 100% volume 
![_5](https://user-images.githubusercontent.com/36737088/36546256-02d307ca-17fc-11e8-9eb8-856952d53e30.gif)

**Comment by afinne** [comment]
Also issues in #112

**Comment by nodeful** [comment]
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by zoltankiricsi** [comment]
+1, hte full-volume mac issue is also present when trying to switch audio source from the menu bar quick access (option-click).

**This is a user safety issue, please give it a high prio.**
Unfortunately discovered this bug using in-ear headphones, my ears hurt like hell :(

**Comment by msegers** [comment]
Well at least happy to see I'm not the only one. I was wearing passive noise canceling headphones and my colleagues heard a lot of noise coming from me. That also means my ears hurt now.

**Comment by Satori83** [comment]
Wow its nice when you find out your not alone lol! I leave my iMac on overnight with the display asleep. It only wakes display for few mins @ 2am for backup. I've had this issue as well and it def seems directly related to the outputs changing at random. I used to think it was the additional devices themselves causing it, for me I thought it was from using it with Zoom, but thats uninstalled and I guess some 3rd party Spotify app added a new device. This morning sat down and turned studio monitors on and some Pandora, and the eQHeartAttack started once again at full blast on my sensitive monitors and still blew my eardrums across the room even without headphones!

Now, I don't wanna just be Debbie Down cause like most of us here, I love this app and appreciate your work. And the new UI looks absolutely SIICK bro. It reminds me of the Viper4Android UI. So I get its time to push forward and not look back, but I agree with some of the other users in that if the new app isn't going to be ready for a bit and obviously u don't want to cut corners, then maybe you would see/understand why this issue is a bit more important. It's not a small UX bug or feature request, unless the feature request is for an Anti-Blowout lock button ;-) I mean yeah it would REALLY suck to inadvertently blow out expensive monitors from an app bug, but even worse is the kid who can no longer enjoy music the same way again because his audiophile grade loud and clear in ear buds just gave him tinnitus because his safe and responsible volume changed on its own to full blast. Dont mean to be doom and gloom,  just trying to highlight the importance here. Again thanks for great software and any advice or support on this matter.

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
