### ISSUE TITLE
Driver install problems

### ISSUE THREAD

**Issue by Overc1ocker** [bitgapp/eqMac#129]
For some odd reason, running the application from the disk image, installing the driver, then moving the app to the applications folder works, and installs the driver successfully, but doing it the other way around doesn't.

**Comment by azharhussain96** [comment]
This worked for me. Also, you may need to click "allow" in the system preferences pane that opens up.

**Comment by nodeful** [comment]
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by wmertens** [comment]
I too had problems, turned out that I couldn't actually click "Allow" because one of my apps (don't know which one) does things with click events and that's not secure. So the workaround is to tab to the "Allow" button and press "space", but you can only do that if you have tab-between-all-interface-elements enabled, which is mapped to ctrl-f7 by default.

**Comment by wiederhold** [comment]
No success with either
<img width="610" alt="screen shot 2018-10-07 at 1 56 57 pm" src="https://user-images.githubusercontent.com/16354737/46586840-fe67e080-ca38-11e8-9c0a-0be1136262af.png">
AND
<img width="610" alt="screen shot 2018-10-07 at 1 59 00 pm" src="https://user-images.githubusercontent.com/16354737/46586853-31aa6f80-ca39-11e8-829e-7c2bee8fd81a.png">
OR
suggested solution at: https://github.com/nodeful/eqMac2/issues/130
in either configuration

Appreciate the work, have installed the product successfully on a previous laptop, but not on this one:

  System Version:	macOS 10.13.6 (17G65)
  Kernel Version:	Darwin 17.7.0

**Comment by slemaster** [comment]
I use MagicPrefs to customize actions for my mouse and trackpad. Turning it off allowed me to successfully click "Allow" and install.

**Comment by OssiPesonen** [comment]
I have the same issue on  macOS 10.15.1 (19B88), Kernel Darwin 19.0.0. Unable to install the drivers. I have tried both App settings, Brew install...

**Comment by doesprintfwork** [comment]
For Catalina, try to remount the System Partition by `sudo mount -uw /` and install again.

**Comment by Crunchyliam** [comment]
I am also having the same issue but I'm on macOS 10.15.2 and I am unable to install the drivers, the box which asks specifically about the app doesn't show up either and typing "sudo mount -uw /" into terminal doesn't seem to work, it says "mount_apfs: volume could not be mounted: Operation not permitted
mount: / failed with 77". 

I apologize if its troublesome that I can't find the "Kernel Darwin" name and I do not understand a lick of coding.

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by slavpetroff** [comment]
> For Catalina, try to remount the System Partition by `sudo mount -uw /` and install again.

That worked for me! Thanks!

**Comment by bawva** [comment]
> Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release.
> You can download it here: https://eqmac.app
> There are a lot of known bugs that I could not fix just yet:
> 
> * Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
> * Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
> * UI takes long to load (a lot can be done to improve that)
> * UI dimensions are not synching properly
> * There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
> * Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.
> 
> So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
> I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
> That repo will become the main repo for eqMac and this repo will be archived eventually.
> And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

Finally this worked! Appreciate all your hard work!!

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
