### ISSUE TITLE
Max volume when starting on Displayport output

### ISSUE THREAD

**Issue by wiredcharlie** [bitgapp/eqMac#140]
When using Displayport output, eqMac2 starts with max volume whilst showing 0. Volume must then be set at the normal speaker icon. I noticed that AppleScript  "set volume 5" works on the master volume / speaker icon.

**Comment by nodeful** [comment]
First of all, I would like to apologize for the lack of communication and responses to the current issue and all other issues in general.
I have made a conscious decision to focus most of my free time and focus on developing a more modern and new version of "eqMac". This means that I can't spend too much time looking back at old codebase and trying to make every user happy. This was the main reason I made this repository open-source, in hopes that other developers might help to sort out some issues and iron out all the bugs. Unfortunately, there are very few developers that are proficient in Core Audio and Objective-C or maybe they are just not interested in this repo, which I can understand.
I promise that the next version will be much more polished and I will make some sort of a mainstream system were solving issues will be very easy and quick. Just sit tight and wait for a new release this coming summer.
Thank you to everyone who gave "eqMac2" a try and I hope I won't disappoint you next time :) 

Heres a sneak peak of the UI I am currently working on:
<img width="460" alt="screen shot 2018-05-07 at 20 14 47" src="https://user-images.githubusercontent.com/8472525/39781257-95ffc156-5306-11e8-84fd-d100518e1676.png">

**Comment by conkur** [comment]
Thanks for the update @nodeful. I'm a big fan of eqMac2, for the time being I have no Core Audio experience, but that might change in hopes of adding another dev to the library.

**Comment by kevinra** [comment]
Wow the new UI looks fantastic! I look forward into the new code base.

**Comment by artistbuddy** [comment]
Hi, I found similar issue with AirPods connected via Bluetooth (different iCloud account). Automatic Play/Pause feature cause problem. If you take out and in one EarPod volume is set to maximum. Mac OS 10.13.6.

**Comment by nodeful** [comment]
https://github.com/nodeful/eqMac2/issues/164

**Comment by erikhuizinga** [comment]
I have this issue too, when I switch from headphones to DisplayPort and back, the headphones volume is 100%. This does not happen when I switch from headphones to the macBook speakers. I think the fact that the volume cannot be controlled from macOS through DisplayPort is the problem.

Visually in eqMac2, the DisplayPort volume is 0%, but it is actually controlled on the DisplayPort device. Switching back to headphones somehow sets 100% volume. Maybe store the last known volume choice and take the `min(lastKnown, systemReported)`, so that you never automatically go to 100% (unless both values are 100%)?

**Comment by Satori83** [comment]
I have a similar issue that is persisting where I have eqmac set to a custom preset and built in output which goes straight from headphones output to Tannoy reference monitors because I removed the Focusrite last year. This has worked great until few months ago it seems if eqMac crashes (i leave comp asleep at night), when I restart it the volume will automatically go to 100% and whether its music or white noise when I push play, I nearly have a heartache, my speakers cry and bleed, its rough.
https://satori-design.d.pr/3xKEnH

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
