### ISSUE TITLE
Sound is crackling (Mojave)

### ISSUE THREAD

**Issue by patczynski** [bitgapp/eqMac#152]
Hi there!

I'm using this great little equalizer since yesterday. Unfortunately I'm experiencing a crackling sound after a couple of minutes when listening to music, watching a movie etc. After restarting the App it's fine again - for a short time. 

MacBook Pro 2018 (13", Touch Bar)
Mac OS 10.14 (Mojave)

Greetings from Germany!

**Comment by ChristianLapinig** [comment]
I am having the same issue. I think it might be a hardware issue because this happened to me in High Sierra with the same laptop before I switched to Mojave. I had eqMac2 installed on my 2011 Macbook Pro and it worked flawlessly even in High Sierra.

**Comment by andhieka** [comment]
I face the same issue on macOS 10.13.6 (High Sierra), MacBook Pro 15-inch, 2018.
Crackling sound only happens after a few minutes, and restarting the app solves the issue. Is there a debug log where we can probably find what's wrong?

**Comment by stpoa** [comment]
Same issue, using dragonfly red DAC.

**Comment by warpkanal** [comment]
Very same issue here as well (mojave). Sound starts crackling after 15-20 mins of listening.
Restarting the app solves the issue for the next 15-20 mins...

**Comment by nnchang** [comment]
same issue on 13" 2018 retina. However, it wasn't a problem for an hour or two when using the EQ together with a bluetooth speaker.

**Comment by dinamic** [comment]
Could it be that you guys are using wireless headphones?

**Comment by patczynski** [comment]
@dinamic I've experienced the crackling sound with wired headphones and inbuilt speakers.

**Comment by warpkanal** [comment]
No wireless in my setup, plain USB sound device with cable connected speakers :)
No crackling e.g. with Boom, so pretty sure some buffers somewhere around eqmac overflow/stall/whatever. Also backed by the fact that restarting eqmac solves the problem for the next 10-20mins

**Comment by jdvirelli** [comment]
Same issue here on Mojave, MacBook Pro 2016– 
The quickest way to deal with it is to reselect your listening device instead of restarting the program.

**Comment by jasongardnerlv** [comment]
Same issue here.  Mojave on 2018 Mac Mini.

**Comment by rhyek** [comment]
Same issue using a 2018 13" Macbook Pro with an Audioengine D1.

**Comment by peteallen** [comment]
Same issue. 2018 15" MacBook Pro with 10.14.1. External speakers connected to the headset port.

It takes a while to develop (two or three songs, so maybe 10 minutes?) I can fix it temporarily by clicking on the eqMac2 icon, and clicking on the output dropdown without changing the selection. The sound cuts out for a couple of seconds and then comes back without the problem.

**Comment by andhieka** [comment]
I noticed that after uninstalling eqMac2, the problem still persists. It seems that the problem might be from Apple (link: https://www.macrumors.com/2018/08/08/2018-macbook-pro-crackling-speakers-reports/). Using eq software just makes the problem appear faster.

**Comment by rhyek** [comment]
I don't think this is accurate. Since I disabled the app I've had no issues with sound.

**Comment by jaybocc2** [comment]
I also get crackling however if i change outputs and reset the EQ or restart the APP it goes back to normal.

**Comment by pavelz** [comment]
Over time iMac 2011 27 radeon plays fine but overtime I get this fuzz and then sound cuts out alltogether. might be some sort of accumulative error. iMac is 24bit and I noticed eqMac2 2.2 processes sound in 32 bit

**Comment by mexitalian** [comment]
I was having the same issue, (Mojave).
Allowing eqMac2 accessability control seems to have fixed the issue.
 
![image](https://user-images.githubusercontent.com/1676515/49463195-78101680-f7bd-11e8-9302-bbddf76fd42b.png)

Hope it helps!

**Comment by Griffinstein** [comment]
I face the same issue on macOS 10.13.6 (High Sierra) and 10.14.1 (Mojave) MacBook Pro (13-inch, 2017)

**Comment by MrMotlo** [comment]
I have written a little applescript to work around. It is not optimal but works.


[eqMac2_restartScript.txt](https://github.com/nodeful/eqMac2/files/2667379/eqMac2_restartScript.txt)

**Comment by qazlint** [comment]
is this solved yet ? I have the same issue. iMac Pro 2017 , and I haven't tried the applescript as suggested above ^^ (hoping this would be fixed in an update), but I might try if this is the only option

**Comment by wstecklair** [comment]
The script from MrMotlo worked like a charm. I use to hear the static after 2 songs, I'm about 15 songs in and no static/crackle. (thanks @MrMotlo )

Here's what I did.... 
Once you paste the script from @MrMotlo (above ^^) in the editor.... go to the menu and.... File > Export > then set File Format to application then save. That'll make it run automatically when you just click the icon. I put the app icon for the script in my menu next to my music player icon, just click them both when opening music and you're set.

**Comment by alfons** [comment]
What is the driver that was forced onto my system? I regret having given permission. Is it possible to replace it with the original Apple driver again? I uninstalled eqMac2 but unfortunately the crackling persists. It's super annoying. How to fix this?

**Comment by Wist9063** [comment]
For me, it starts to happen when I start playing bass intensive music or just put the volume up.

**Comment by Kieleth** [comment]
Finding similar issues with Mojave 10.14.2. I've reproduced this in both USB external DAC as well as directly connecting headphones to the Mack minijack:
- Set master volume to 100% 
- Choose and pick any combination of sample rate/ bit depth, tried most of them.
- Set as little as +5dB on these three: 50, 63 and 80Hz.
- Play any good bass-heavy song, like Bike from Autechre, from second 30+
It will distort and crackle big time.

**Comment by AustinGomez** [comment]
Mojave 10.14 here, 2018 Macbook pro. I get crackling almost instantly now. Also the audio deteriorates quickly as well, sounds like very heavy clipping. 

Unfortunately unusable

**Comment by peterharding** [comment]
Same issue, Mojave 10.14.2

**Comment by akaleMulder** [comment]
Worked as a charm on my old MacBook Pro late 2012 but crackles on my MacBook Air 2018.

**Comment by dissovldgrl** [comment]
> My early-2016 Macbook (Movave 10.14.2 18C54) works fine.
> My late-2015 iMac (Mohave 10.14 18A391) crackles horrible every few minutes.
> Update: I upgraded my iMac's OS (from Mohave 10.14 to 10.14.3) and the crackling seems to have vanished.

This worked for me too.

**Comment by artuj** [comment]
MBP 15'' 2018. Upgrade to Mohave 10.14.3 only extended the time, when the crackling appears again.

**Comment by dastamatis** [comment]
> MBP 15'' 2018. Upgrade to Mohave 10.14.3 only extended the time, when the crackling appears again.

Yeah, I do still notice the occasional crackle, only perhaps once or twice an hour, and much more subtle and quite than before. Versus prior to the upgrade, where the crackle was louder and happening every 2 or 3 minutes.

Not perfect, but it's definitely mitigated to the point of being tolerable.

**Comment by dissovldgrl** [comment]
> > MBP 15'' 2018. Upgrade to Mohave 10.14.3 only extended the time, when the crackling appears again.
> 
> Yeah, I do still notice the occasional crackle, only perhaps once or twice an hour, and much more subtle and quite than before. Versus prior to the upgrade, where the crackle was louder and happening every 2 or 3 minutes.
> 
> Not perfect, but it's definitely mitigated to the point of being tolerable.

yeah it's back for me too after a while of listening. darn. it definitely did decrease the frequency of crackling, though.

**Comment by kurevin** [comment]
Pretty much any old audio software suffers from this issue, Soundflower included...the only temporary fix is restart said software regularly.

**Comment by akaleMulder** [comment]
> The script from MrMotlo worked like a charm. I use to hear the static after 2 songs, I'm about 15 songs in and no static/crackle. (thanks @MrMotlo )
> 
> Here's what I did....
> Once you paste the script from @MrMotlo (above ^^) in the editor.... go to the menu and.... File > Export > then set File Format to application then save. That'll make it run automatically when you just click the icon. I put the app icon for the script in my menu next to my music player icon, just click them both when opening music and you're set.

The problem with the script is that once it restarts the eqMac (which is the main idea of the script I suppose), the focus of the system gets into the eqMac. So, when I am typing something, my cursor vanishes from the form I used to enter the text. Which makes this workaround totally unusable =(

**Comment by Wist9063** [comment]
I think I found a quick fix for now, try switch bands when it starts to crackle. Works on my iMac (21.5-inch, Late 2015) on Mojave 10.14.2 (18C54).

**Comment by Ethan-Newthink** [comment]
> I think I found a quick fix for now, try switch bands when it starts to crackle. Works on my iMac (21.5-inch, Late 2015) on Mojave 10.14.2 (18C54).

What does that mean, to switch bands?

**Comment by Wist9063** [comment]
>> I think I found a quick fix for now, try switch bands when it starts to crackle. Works on my iMac (21.5-inch, Late 2015) on Mojave 10.14.2 (18C54).<br>
>
>What does that mean, to switch bands?

![screen shot 2019-02-18 at 4 48 40 pm](https://user-images.githubusercontent.com/22089269/52982845-414da380-339d-11e9-9fd2-e5c2fced0f3a.png)

Once I switched the bands it removed the crackle, but in a while the crackle starts to come back. When that happens just switch the bands back and just repeat.

**Comment by cjmaria** [comment]
In addition to eqmac, this issue also occurs when using soundflower and AU Lab's equalizer and other software. This is most certainly an issue with some Apple driver or Core Audio, but it looks like there is no good solution at the moment (and there has been none for years). If someone has knowledge of this domain and could investigate the actual source of the problem, maybe an open source solution could be made.

**Comment by ethansaks** [comment]
> @peteallen Ok here are the full steps undertook for the problems to go away.
> 
> * Get frustrated and decide to try out  https://staticz.com/soundcontrol/ (trial)
> * Open, it will update its audio driver for Mojave (requires restart).
> * Then it asks for the accessibility permission (shown previously).
> 
> I copied this permission for eqMac2, but I think it's reasonable to assume Sound Control probably uses SoundFlower behind the scenes, so the driver update seems to have fixed eqMac's issues.

Are you finding that this fix is still working for you?

**Comment by dastamatis** [comment]
I gave up entirely on all Mac-based EQ software. Not worth the hassle. Instead, I upgraded my headphones, to ones that don't require EQ. Problem solved... by avoid the problem in the first place.

**Comment by tweichart** [comment]
I ended up using Boom3D, it doesn't seem to have a problem with any cracking sound and works as expected. In the end though I don't use it that much either, having headphones that don't need an EQ in the end too.

**Comment by Psynbiotik** [comment]
Another interesting thing is when switch between bands as @Wist9063 suggested when I come back to the band all the values are severely increased, I wonder if this is the root of the issue, this values keep increasing behind the scenes until the sound is distroted.

**Comment by artuj** [comment]
macOS 10.14.5 update was just released. Looks promising :)

> Improves audio latency on MacBook Pro models introduced in 2018

**Comment by m652i** [comment]
Still crackles after around 5-10 min in. Using the auto restart script atm. 

Have good headphones, but still like to have EQ for different things I'm listening to. This is the only one that has a 31 one band EQ, as most of the other choices only have 10 band. 

Have tried almost every other options (menuBus, Sound Control, Sound Source, Audio Hijack), nothing is as simple and as easy to use as this one. 

Honestly dev, I'd pay money for this plugin. 

Maybe we can looking into menuBus or Sound Source to find solutions to this crackling problem. 
Either way thanks for making this, highly appreciated!

**Comment by alfons** [comment]
October 2018 I bought the new MacBook Pro 2018 13 inch. Didnt notice any issue with sound. Had to return the MacBook though because of a discolouration issue on the touchpad. Got my MacBook Pro back after one week wait, they had to replace the entire topcase. Crazy.  Also bought expensive, wired headphones. Figured I need an equalizer. Downloaded and installed this. Had crackling in my expensive headphones. Checked with all my other wired headphones, same issue. No issue via bluetooth or MacBook Pro speakers. Did a clean reinstall of Mojava. Still had the crackling. Spent almost 3 hours on the phone with support. No solution, they couldnt understand what I was talking about in the first place. Didn’t want to turn in my MacBook again. At that point bit desperate to be honest. Thought I will try fixing this with professional software. Downloaded Air Foil from Rogue Amobae, the cheapest “real” equalizer I could find. It’s very basic and a bit inconvenient to use (works only on a per app basis), but it does the job: it removes the crackling. Still disappointed by what Apple sold me for 2500€.

**Comment by andhieka** [comment]
Hopefully this will solve our issue. Haven't tried it yet. Finally Apple acknowledges the problem and tries to fix it.

![image](https://user-images.githubusercontent.com/6689743/58150595-ac0ec380-7c99-11e9-88d4-6de90f20d92d.png)

**Comment by rhyek** [comment]
Can someone confirm if that update helps?

**Comment by clridd** [comment]
Installed the update on my 2018 MBP yesterday and the issue still persists. I've been reselecting the audio channel with my headphones in every couple songs as I'm listening to music.

**Comment by chrisgross** [comment]
This issue goes way back. Still no solution.

[Sounds degrade after 30 minutes playing aprox](https://github.com/nodeful/eqMac2/issues/36)

[Sounds starts crackling and after a while completely turns off](https://github.com/nodeful/eqMac2/issues/79)

[eqMac2 problems](https://www.reddit.com/r/headphones/comments/am5hv4/eqmac2_problems/)

**Comment by nodeful** [comment]
https://github.com/nodeful/eqMac2/issues/164

**Comment by ggalindezb** [comment]
Same issue, MBP@10.14.6, output through a uDAC3 Async running at 32 bits 44.1 KHz. The Accesibility workaround seems to have delayed it quite a bit, but it comes back. Restarting definitely fixes it.

@nodeful Is there any log to check? Maybe I can track the error down and give it a shot.

**Comment by TheKuyPeD** [comment]
![image](https://user-images.githubusercontent.com/25427961/64582637-5f6e0600-d3b8-11e9-875d-95ea07857080.png)
My solution is change the audio format from 48,000Hz to 44,100Hz. Hope that help you.

**Comment by chad-cros** [comment]
I made a short little script that waits until the song has finished playing before restarting eqMac. If anyone is interested in it, you can find it here:
https://github.com/chad-cros/eqMac2-Helper

**Comment by pforhan** [comment]
I'm not saying macos has no problems, but the fact that you can manually switch between 10 and 31 bands to clean up the issue means that the software can probably mitigate this issue.

**Comment by UnbearableBear** [comment]
Gosh this is so so sad. Led zeppeling without an equalizer is a real pain and so is the crackling, this world is ROUGH

**Comment by MariuzM** [comment]
Still same issue, trying 10 bands for now it's fine, mostly getting issues with 31 bands. Mojave, MBP and Dragonfly Cobalt.
I'm guessing this is not hardware issue but a glitch in this app, shame that creator is ignoring and not posting anything about this issue.

**Comment by Joachim-42he** [comment]
@MariuzM The creator has posted about this in other issues.
https://github.com/nodeful/eqMac2/issues/164

**Comment by bencodesall** [comment]
> ![image](https://user-images.githubusercontent.com/25427961/64582637-5f6e0600-d3b8-11e9-875d-95ea07857080.png)
> My solution is change the audio format from 48,000Hz to 44,100Hz. Hope that help you.

@TheKuyPeD What is that app you have the screenshot of?

@patzynski @nodeful
#152
UPDATE:
- It’s the native macOS Audio MIDI Setup utility (in /Applications/Utilities folder)
- I made the change and it seems ok for now.
- Will update if crackle comes back.
- This makes perfect sense due to codec bit drift when frequency is mismatched.
- User guide / Wiki should show how to make this settings. This makes it a “non” issue!!!

**Comment by MariuzM** [comment]
> ![image](https://user-images.githubusercontent.com/25427961/64582637-5f6e0600-d3b8-11e9-875d-95ea07857080.png)
> My solution is change the audio format from 48,000Hz to 44,100Hz. Hope that help you.

So this is basically matching your file to output right but what if you have multiple files with diff frequencies are you going to constantly change them depending on file? This option is valid if you have a lot of if not all files with same frequency but apart from that I don't think this i will work.

**Comment by chrisgross** [comment]
The frequency and depth settings do not really matter in this case. The crackling still comes back eventually, even if they match. I've also had this issue with 10 bands, so that is also not the solution. There is clearly something inherently wrong with the app.

**Comment by bencodesall** [comment]
Could there be an implementation problem in the RingBuffer using Int instead of Float precisions? `CARingBuffer.h` is mixing signed and unsigned ints. Could it be an accumulation of buffer overflow/underflow? Only took a cursory look at the code just now, and I'm not a macOS dev. Just spit balling here.

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by palmereldrich** [comment]
Bro, really nice! Hope the problem is gone. If so, this is the best eq app for Mac ever. Congrats ant thx for the efforts!

**Comment by Gairth** [comment]
After trying everything else...
I went to eqmac.app...the new "beta" version.
Despite all the caveats and reported issues....

IT WORKED FLAWLESSLY! For me at least.

I love it. Very pleased.

Thank you to the developer for his generosity.
You truly rock!

G

**Comment by kcwebdesign** [comment]
I was having these exact issues. First of all I thought it was my vintage amp playing up so swapped it out for another - still got same issue. I'd got a new DAC so that was my next thought. Changed DAC, same problem. I had eqmac2 installed but hadn't really been using it so used the uninstall option. Still got the same crackling/distorted sound. While trying some other fixes I noticed that eqmac2 was still showing as an option in my sound control panel and midi setup even though I'd uninstalled it. So, I did a finder search for 'eqmac2' and blow me if a bunch of files didn't show up. Some of them couldn't be removed for some reason (_/Library/StagedExtensions/System/Library/Extensions/eqMac2Driver.kext - can’t be modified or deleted because it’s required by macOS?_) but the other files and some folders where deleted and the Mac restarted. Now in my control panel and midi options there was no eqmac2 option and, fingers crossed, the crackling has gone (2 days now)!

So be aware. Looks like eqmac2 is the cause BUT it does not fix the issue if you uninstall the app, **YOU HAVE TO REMOVE ALL EQMAC2 FILES MANUALLY**.

I hope this helps others as this problem has been driving me nuts for months!

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by hanrok** [comment]
> Hey everyone 👋
> I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
> Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
> Please try out the new version and report bugs to the new repo.
> Thanks for using eqMac.

I downloaded the app from https://eqmac.app/ but still have noise and "crackling sound" after a while.. :(

**Comment by nodeful** [comment]
Moving discussion and tracking of this issue to #224
