### ISSUE TITLE
Can't hear difference on eqMac2 when I moved up the sliders of the EQ?

### ISSUE THREAD

**Issue by erwinxxx** [bitgapp/eqMac#154]
I just installed eqMac2 on my Mac Mini with bluetooth speakers but can't hear difference when I moved up the sliders of the eq.  When I moved up the volume in the app it works it's full open but when I put more treble in it and bass I hear no difference. And also no sound on websites with sound on my FireFox browser. What's wrong?

**Comment by Dale-Cotton** [comment]
With no expertise in either MacOS or Bluetooth I'm the last person to answer this, but no one else has responded in 4 days. Probably, the following will be too basic, but it might at least start things going:

When my son comes over with his Bluetooth headphones, he first makes a BT connection with my computer, then his headphones become available as an item in both the drop-down from the little speaker icon in my menu bar (top right of my screen), and in the output selection drop-down box in eqMac2. The screen shots below are from my system right now so my son's headphones aren't listed. (If you don't have the little speaker icon in your menu bar, you can accomplish the same thing in the Sound Preferences dialogue box from your System Preferences.)

I don't remember what the correct choices would be. But try selecting eqMac2 in the menu bar drop-down to route your system sound to eqMac2. Then select your BT speakers in the eqMac2 drop-down to route eqMac2's output back to your system so it can pass the signal on your speakers. If no joy, try the other combinations of selections in those drop-downs. If still no joy, leave your BT speakers showing in the eqMac2 drop-down box, then try quitting and re-starting eqMac2.

If **still** no joy, perhaps post screen shots from eqMac2, plus both the Input and Output screens from the Sound Preferences dialogue box, plus also screens from the Audio MIDI Setup app (launches from Finder->Applications->Utilities). Perhaps also add the Bluetooth configuration dialogue for good measure:

![image](https://user-images.githubusercontent.com/16454622/48783764-38bad380-ecaf-11e8-97ad-84c9d77b50bd.png)
![image](https://user-images.githubusercontent.com/16454622/48779031-b75e4380-eca4-11e8-9163-a7745603786f.png)
![image](https://user-images.githubusercontent.com/16454622/48783878-70c21680-ecaf-11e8-9618-41f3e8ccb29d.png)
![image](https://user-images.githubusercontent.com/16454622/48780136-2ccb1380-eca7-11e8-8e8b-dab426b4e208.png)
![image](https://user-images.githubusercontent.com/16454622/48780148-36547b80-eca7-11e8-8ac7-67571f1b1d4d.png)
![image](https://user-images.githubusercontent.com/16454622/48780161-3e142000-eca7-11e8-8c58-cf221cb24f5c.png)
![image](https://user-images.githubusercontent.com/16454622/48781056-3c4b5c00-eca9-11e8-99eb-5d4cbb09779c.png)

**Comment by erwinxxx** [comment]
Ok thanks. It's working fine now. I think one of the volume sliders was too low.

**Comment by nodeful** [comment]
https://github.com/nodeful/eqMac2/issues/164

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
