### ISSUE TITLE
Presets switching for speakers and headphones/3.5mm jack?

### ISSUE THREAD

**Issue by Intenditore** [bitgapp/eqMac#165]
I've read what you told not to post here, but I took a look into the Slack and it's abandoned. So... 
The very simple but extremely needed thing - separate presets for headphones and speakers and automatic switching between them. 
Can it be implemented? Any workaround with Automator maybe? That's very, very handy feature I found nowhere((

**Comment by nodeful** [comment]
I will try to make it happen for the next version of eqMac

**Comment by Intenditore** [comment]
Awesome!
You know, I think you should try something like Kickstarter to gather some funds for the developments. I'd like to support you a bit, sure there are others who need this app too.
Maybe?

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by Intenditore** [comment]
You're making a great utility, and this is amazing you're releasing the source, but I think it's better to make this tool a paid one to gather funds and develop it more and more. It's awesome you do it this way, but I could even pay for this software, not too bad for us and good to you

**Comment by nodeful** [comment]
I just don't have the time to work on it too much as I have a very busy life and frankly I'm not super interested either. I will keep poking around still, I just think it's better if the source code is free to be poked around by anyone else

**Comment by Intenditore** [comment]
Oh, I'm afraid it wouldn't be good for the evolvement.. Don't you have somebody who will push the development? 
I don't have enough confidence(

**Comment by nodeful** [comment]
Moving discussion to #231
