### ISSUE TITLE
no sound on boot, general hardware issues, call for dev contributions 

### ISSUE THREAD

**Issue by brian-lamb-software-engineer** [bitgapp/eqMac#166]

**Comment by brian-lamb-software-engineer** [comment]
Hello, I would like to say this is an awesome app, and i really appreciate your efforts.  I would also like to say, can we get some help here?  Doesnt anyone have time to contrib, who has skills in this area?  This app is near polished, but has some minor hardware issues from what i can see.   

So i have been an 11 month continuous user, across two macs, one latest gen probook,  other previous gen, all latest os version.  

Lately, my latest gen mac, mojave, starts with no audio.  Im using HDMI audio this time, i have a usbc to hdmi.  That monitor has a 1/8th output jack that i like to use so that i can carry it digital to that point.    

at boot, the sound device is pointed to eqMac. I have to physically point it to DellMonitor, to get the sound to come back on. Today unfortunately i missed an important meeting.  my bad..  I hadnt noticed that the sound wasnt toggled on yet, i needed to toggle it to teh Dell, from eqMac, in order to get the sound to initiate.  I have to do this at every boot, i forget to do this alot until i turn on some music, then i realize my audio was off the last few hours, i go into panic, what have i missed, rinse and repeat.  you get the point. 

Prior to that, i would join a slack call, only to realize the audio was intermittent, and i could only reboot, until i realized `sudo pkill eqMac` solved it.   this came back regularly until i switched  macbooks or something.   

Guys, I love having this eq on my system. Is there any other developers out there, or Roman are you willing, i see a pull request waiting now.  

I think this source code is close to being the best EQ Mac has, so please, somebody please consider if you have the time to get this spruced up a bit, or make your suggestions.  Roman seems swamped, and this thing is too cool to scrap.  

Ill admit it just brew cask reinstalled it, beacuse i couldnt brew cask uninstall it, because i forgot i had installed it from brew, when i trashed it from the applications menu, meanwhile grepping for traces.  

I decided to turn to this post first.  

Thanks for any help, on behalf of eqMac, the bad ass little eq for mac.

**Comment by VSG24** [comment]
I'm also having this issue. There is no sound at boot and I have to use the system audio controls to switch to another output and it immediately goes back to the original output and works fine but there is no sound at boot.

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
