### ISSUE TITLE
Q factor?

### ISSUE THREAD

**Issue by busheezy** [bitgapp/eqMac#167]
Hello, I am currently using Equalizer APO on Windows and I want to have my buddy use the same corrections as me. I don't see eqMac2 having the ability to adjust the Q factor. Is this something that might eventually show up in eqMac? Is Q factor going to affect the results a ton? I'm not too familiar with this. I just know the corrections I downloaded for my speakers sound really good.

https://share.busheezy.dev/tRoBWe
An example of my current config.

Thanks

**Comment by Dale-Cotton** [comment]
> I don't see eqMac2 having the ability to adjust the Q factor. Is this something that might eventually show up in eqMac?

Not only would you need to specify Q values, you would also need to be able to specify center frequencies to duplicate the EqualizerAPO approach in eqMac2.

> Is Q factor going to affect the results a ton?

So far as I can tell, it shouldn't make an audible difference, at least in what you're doing.

**Some background**
There are at least two very different types of EQ. EqualizerAPO is parametric (PEQ); eqMac2 is graphical (GEQ). Parametric EQ solutions allow the user to assign 

- a frequency
- a decibel amount
- a band width (Q) 

to each correction point he makes. Graphical EQ solutions simplify this by providing a fixed set of frequencies and a fixed approach to Q, leaving the user only able to adjust the decibel amount. Because eqMac provides 31 fixed frequencies to work with (1/3 octave values), the theory seems to be that this allows sufficient precision for anyone's needs, while having a simpler, easier-to-understand interface.

Nodeful reported in this most recent update (https://github.com/nodeful/eqMac2/issues/164) that eqMac3 will **not** have major changes to version 2's functionality, so presumably no PEQ. Version 3 will mainly be a change to the visual interface and a fix for reliability issues. But he also indicated there may be enhancements to follow version 3. I asked whether PEQ would be one of them, but he has not replied.

**Possible work-around**
To approximate in eqMac2 the audible portion of the EqualizerAPO graph you provided, try entering these dB values in the 31-band portion of eqMac2:

![image](https://user-images.githubusercontent.com/16454622/59965091-bfe75880-94d7-11e9-8519-f9648fd7245f.png)

(dB numbers show at the bottom of each vertical line in the grid, starting with 7, 7, 6, 6, 2. No great precision should be required.) See how that sounds. I’m puzzled how this would help unless your friend has identical room acoustics, but I probably don't understand what you're doing.

**Comment by busheezy** [comment]
Hey @Dale-Cotton. Thanks for the explanation. Sorry for not replying. I'll have my buddy give that a try.

**Comment by oalmali** [comment]
@busheezy you might want to check menubus you can add aunbandeq which would allow you to enter width for each frequency as well as decibel values. It is not actively supported anymore but I am using it with macOS Mojave without any issues.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/5868341/63755776-88ba6c80-c8b7-11e9-931c-4046ff7eb65b.png">

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by nodeful** [comment]
closing in favour of #252
