### ISSUE TITLE
EQMac2 requires a driver update!!!

### ISSUE THREAD

**Issue by Ashteroide** [bitgapp/eqMac#177]
I have tried multiple solutions and none have worked, I've allowed anything, I'm running macOS Catalina 10.15.2 (beta). Please help with this, I've tried multiple things, manual kext installation, brew cask install eqmac. I get a popup when I open EQMac2 saying it needs a driver update. I do as follows but have to quit it.

**Comment by i3p9** [comment]
I'm also having the same issue, unfortunately.

**Comment by MariuzM** [comment]
Forget the v2 it has more issues than that, dev is working on v3.

**Comment by jdchmiel** [comment]
Interesting, this must be an issue with installation. I have eqMac installed on Mohave, updated to Catalina, and it is still working mostly fine ( volume issues with bluetooth device, volume level jumping when output device changes, other known bugs etc.)

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by Ashteroide** [comment]
This little penguin is ready to dance thanks to the new beta version of EQMac, it works on Catalina now which is awesome. Now I can enjoy my bass tunes all day

**Comment by Keeg007** [comment]
OMG YESSSS! IVE BEEN LOOKIN FOR A EQ FOR MAC AND I JUST DOWNLOADED THE BETA ONE AND NOW MY AIRPODS HAVE SOO MUCH BASS

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by outhousetickets** [comment]
I'm SO glad you got a new version released. It's so much better than no EQ. But, the old version used to produce the most amazing bass in my headphones and no longer does. The previous version had way more frequencies to adjust. Is this coming in the next release (please!)?
