### ISSUE TITLE
eqMac beta v0.0.1 : Sound crackles and distorts with USB DAC

### ISSUE THREAD

**Issue by nadstaky** [bitgapp/eqMac#199]
Can't listen to more than one Minute of Music with my USB DAC

**Comment by rushi** [comment]
I play music through my USB-C monitor and am running into the same issue. There is a lot of crackling and distortion after about a minute or so. Restarting the app fixes the issue, but only for a short while.

**Comment by Joachim-42he** [comment]
Same here. I had not yet pinpointed the issue to the usb-conenction but I have the Mcbook connectd to a monitor through USB-C and am playing sound that way.

**Comment by ddrt** [comment]
I'm using 2ch 32 bit float 41kHz with Beyerdynamic DT 770 pro 32 OHM and they worked perfectly with the older version. The newer version doesn't seem to have the same bit depth or channel options under the "format" drop-down in the Audio MIDI application that is used to control sound at a better level between devices. 

Since that's missing this isn't going to work with many headphone and audio setups and isn't a great solution for an app to override or otherwise degrade sound quality by installing an audio driver that creates a system wide change rather than a unique change. 

Does this app, by chance, install older (i.e. Outdated) audio drivers? If so, why did you install them rather than instructing users to enable older drivers through the native Audio MIDI app? And if that's the case please let us know how you plan to use modern drivers since the outdated drivers will not scale.

**Comment by nodeful** [comment]
Moving discussion and tracking of this issue to #224
