### ISSUE TITLE
Feature: Add option to have no dock or menu bar icon

### ISSUE THREAD

**Issue by artificial-aidan** [bitgapp/eqMac#221]
I'd like eqMac to just run silently in the background. It would be great if there was a 4th option.
Dock, Both, Menu Bar, Neither

**Comment by nodeful** [comment]
How would you open eqMac to control the audio setting tho?

**Comment by artificial-aidan** [comment]
By opening the app in the application menu. I use another app, better touch tool. Which let's you close the app, and runs in the background. Then when you open the app again it lets you control it. 

The only change to the user experience would be closing eqMac would not quit it, just silently run it in the background.

**Comment by nodeful** [comment]
Would need more feedback from other users as to how useful is this feature.
It would require some time to implement and it's low priority at the moment.

**Comment by carlos-deoliveirafilho** [comment]
I guess this would be good too! =]

**Comment by ssent1** [comment]
In the long-run, +1 for the option of _no dock or menu bar icon_ would be nice. Right now, stability is job №1 since it fails to launch more often than not on my machine. 

Here are four suggestions to consider for a headless implementation.

1. Run the app as a preference panel.
2. Implement a universal shortcut to open the main controls or preferences.
3. If the app is already running, 'opening' it a second time either opens the app or presents a choice of opening the app or changing settings
4. Launch, configure, &/or add additional functionality via a terminal-based command-line.

**Comment by d3ddd** [comment]
I agree this would be great even though it's not important. I also agree with @artificial-aidan that [Better Touch Tool](https://folivora.ai/) has a pretty good implementation for this. It's similar to @ssent1's third option where you open BTT while it's already running to get access to the primary app window. While BTT is running there is no dock or menu bar icon which keeps things simple and clean as a user.

**Comment by nodeful** [comment]
This has been implemented for a while now by the "Neither" option in the eqMac settings, I think since v1.2.0 so I will be closing this issue. Thank you
