### ISSUE TITLE
Feature: Give ability to transfer old eqMac2 preset into new eqMac

### ISSUE THREAD

**Issue by nodeful** [bitgapp/eqMac#234]
**Disclaimer:** 
Please go through [existing feature requests](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Description:**
As requested in #198 #120

Some users have legacy presets that would take a while to recreate in the new eqMac. Should provide ability to easily transfer those.

**User flow & interface:**
Should just add a button in the Advanced EQ settings menu.

**Comment by LeeBinder** [comment]
Hi nodeful - I say YES to this feature 👍

**Comment by nodeful** [comment]
This issue should be resolved in [v0.3.1](https://github.com/bitgapp/eqMac/releases/tag/v0.3.1).
Please update the app and let me know if this issue is still relevant. Thank you
![image](https://user-images.githubusercontent.com/8472525/85286310-4b4c4e80-b48a-11ea-8676-d8d8552b1669.png)

**Comment by LeeBinder** [comment]
When I click onto "Import eqMac2 Presets" nothing happens. I guess because eqMac2 still needs to be installed parallel to current eqMac? In the meantime I had restored my eqMac2 presets which were important to me from screenshots and uninstalled eqMac2, so no way to test anymore.

Exporting/ importing works, but already existing entries are not overwritten (which they should) but after import show up in the list as duplicates. Unless you introduce a query + a little user input window:

Preset $presetName already exists: overwrite?
 ◎Yes ◎No ☐ Apply to all
[Continue]

any preexisting preset should be overwritten, to avoid redundancy.

Anyway, thanks for this state of the presets export/ import module, I appreciate it 👍

**Comment by nodeful** [comment]
eqMac2 doesn't need to be installed, but the /Users/<user>/Library/Preferences/com.bitgapp.eqMac2.plist file with the saved presets should still be there to read. If you used some AppCleaner to uninstall eqMac2, chances are you deleted it.
Regarding importing without checking for duplicates, I went with this method as it was less fragile and complicated and would avoid users loosing any data, just delete the duplicates.

**Comment by LeeBinder** [comment]
yes, AppCleaner, so ~/Library/Preferences/com.bitgapp.eqMac2.plist got removed.

duplicates: fair enough 👍

**Comment by danieltroger** [comment]
Hello, I have 31 band presets but they don't get imported. Am I missing something or is the new version worse than the old one?
