### ISSUE TITLE
Bug: app not starting due to SIGSEGV

### ISSUE THREAD

**Issue by gobozov** [bitgapp/eqMac#236]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Eqmac not starting after fresh installation

**Steps to Reproduce**
1. Download eqmac installer from https://eqmac.app/
2. Install the app by dragging eqmac into Application folder
3. Find eqmac in Applications and double click on it.
4. See nothing happen

**Expected behaviour**
Expect to see eqmac running

**Setup information:**
 - Audio device used for playback: Macbook speaker
 - Audio transmission interface: 
 - macOS Version: 10.15.4
 - eqMac Version  0.0.1
 - eqMac UI Version [e.g. 0.0.4] **(if UI related issue)**

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 
[eqMac_2020-04-20-020140_macbook.txt](https://github.com/bitgapp/eqMac/files/4502329/eqMac_2020-04-20-020140_macbook.txt)

![image](https://user-images.githubusercontent.com/1263794/79734278-4d880600-82ab-11ea-88bc-16d9648369f2.png)

**Comment by edocabhi** [comment]
I had this same issue. Somehow was able to launch it in the beginning but when I connected my wireless headphone and started playing around the app crashed and couldn't reopen until I restarted my Mac. Again after the restart, it worked once and then the same issue.

**Comment by gobozov** [comment]
Restarted macbook many times, it didn't help

**Comment by edocabhi** [comment]
@gobozov Yes it is a bug as restarting is not an option. Maybe I was lucky that the bug was not triggered then. Definitely needs a fix for such a great tool. Sad that I had to uninstall because of this bug.

**Comment by nodeful** [comment]
Not sure what's going on there. Seems like a Segmentation Fault but need to look into it further.

**Comment by gobozov** [comment]
I was trying to fix another problem on my macbook when youtube not playing after sleep. I came across this article https://support.apple.com/en-us/HT204063, did NVRAM reset and seems it fixed issue with eqMac as well. So it works now.
Thanks.

**Comment by nodeful** [comment]
Thanks for your find @gobozov 
I will close the issue for now, if this specific crash occurs again please reopen the issue.
Thanks

**Comment by PaulMcAdam** [comment]
Resetting NVRAM didn't work for me. It still forces you to use 44.1KHz or it won't start. Possibly other people resetting NVRAM reset their settings to 44.1KHz so solved the startup problem. However for me leaving it on 44.1KHz causes the crackling issue after 15-20 minutes. Setting it to 48KHz resolved this for me previously but this is no longer possible.

I also have Zoom installed that forces 48KHz. I suspect the crackling is because I can't set all outputs to the same setting. 

Are there build instructions? I'm happy to do a build and try changing [this](https://github.com/bitgapp/eqMac/blob/ba3d98b2fb73f42539a2cfd582d0d8d137474bbc/native/app/Source/Audio/Engine.swift#L92) myself am unfamiliar with Swift and Xcode.
