### ISSUE TITLE
Cannot select audio output via app // system-wide audio output stuck on "eqMac"

### ISSUE THREAD

**Issue by jayknowstheway** [bitgapp/eqMac#255]
**Disclaimer:**
Please go through existing issues to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.

 I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
- Clicking the "Select Output" dropdown does nothing inside the app.
- Changing the "Select Output" dropdown on the app is possible to do by changing mac's system audio output. However, doing so will likely cause the app to crash.
- While eqMac is active, system output is not able to be changed away from eqMac. Not sure if this should be a separate issue, but there seems to be an issue in how system output and eqMac's selected output relate.

**Steps to Reproduce**

1. Open eqMac and attempt to click or select "Select Output" dropdown. Note that this is not possible.
2. With eqMac open, change system audio output from "eqMac" to "Headphones" on the mac's audio preferences. If app crashes, restart app and go to step 3.
4. Observe the "Select Output" dropdown (should now read "Headphones").
5. View the mac's system audio output. It will read eqMac even though it was previously changed to "Headphones". Attempt to change it and check back. It should still say "eqMac" even though a different option was selected.

**Expected behaviour**
- The "Select Output" dropdown should change the audio output of eqMac.
- The mac's system audio output should be able to be changed independently of eqMac's output.

**Additional information:**
I'm trying to use eqMac to eq all output to headphones. At the same time, I'd like another audio chain to route computer output and record it without any EQ filters. Therefore, eqMac can't be synonymous with "Master audio output" and be inherently linked to my mac's system audio. I'd like two audio routings: one to listen with EQ, another to record without any effects. For this reason I'm still using eqMac2.

**Comment by nodeful** [comment]
Thanks for your comments, but why you haven't followed proper Bug issue template if you feel like the behaviour is not right?

**Comment by jayknowstheway** [comment]
sorry @nodeful I didn't realize there was a template before.. have updated please let me know if it needs correction. I am liking your general idea of where this app could go.

**Comment by nodeful** [comment]
So...
I've never experienced the Select Output dropdown not being populated with any options, you should always have at least one like "Headphones" or "Built-in Speaker" so I can't really reproduce your issue... 
In terms of eqMac always switching over to the eqMac device, that is expected behaviour and I there is no way to avoid it, the eqMac device has to be active for the app to grab the system audio feed. I know just 1 app that somehow circumvented that but they have like a massive team of Apple Audio engineers working on this stuff. I just don't have such resource to do the R&D.
In terms of Recording the system audio without any effects, you can just disable the EQ and record the audio using Quick Time player. But [as per the Roadmap](https://github.com/bitgapp/eqMac#roadmap) this feature is actually going to be eventually baked directly into eqMac.
I will close this issue for now and mark is as "wontfix". The only thing that can be discussed further is  the Dropdown not populating with Audio Devices if more people report this issue and provide more information about their hardware setup.
@jayknowstheway just curious what's the output you get when running this command in Terminal.app: `system_profiler SPAudioDataType`
