### ISSUE TITLE
Anything I can do to help?

### ISSUE THREAD

**Issue by eric-hu** [bitgapp/eqMac#26]
Hi @nodeful !

First I just want to say thank you for creating this app. I use it every day and find it extremely useful.

I'm curious if there's anything I can do to help out with development. I'm a web developer not familiar with macOS programming, but I'm willing to learn.

(Feel free to close this issue, I just wanted to get a message to you somehow and didn't see an email address in your profile.)

**Comment by nodeful** [comment]
Thanks for offering your help Eric!

Unfortunately this is not a project that could benefit a lot from the community in terms of development on the audio processing side. It's very niche technology that a lot of devs would find very frustrating to work with.
Also, I'm planning to make this project commercial at some point, and I don't want to ask people to help me for free just to get all the benefit afterwards.
I am planning to open source the UI side and the website eventually (both written in Angular, but might swap to React at some point) so that the community can make it better for everyone.

Thanks again.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
