### ISSUE TITLE
Info request: cloud you please explain me, why internet connection was required for a locally running application?

### ISSUE THREAD

**Issue by opntr** [bitgapp/eqMac#346]
As you've mentioned here https://github.com/bitgapp/eqMac/releases/tag/v0.3.1 the previous version required internet connection for proper working to render the UI.

What's the root cause behind this behavior?
Why were mandatory before to allow internet connection to the app?
What the do over internet and why?
What will be the https://ui-v1.eqmac.app url?
~~~
op@mongoose:~$ dig ui-v1.eqmac.app 

; <<>> DiG 9.10.6 <<>> ui-v1.eqmac.app
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39209
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ui-v1.eqmac.app.               IN      A

;; ANSWER SECTION:
ui-v1.eqmac.app.        300     IN      A       104.28.16.21
ui-v1.eqmac.app.        300     IN      A       104.28.17.21
ui-v1.eqmac.app.        300     IN      A       172.67.129.57

;; Query time: 47 msec
;; SERVER: 2001:730:3eb2::10#53(2001:730:3eb2::10)
;; WHEN: Wed Jul 29 20:22:42 CEST 2020
;; MSG SIZE  rcvd: 92
~~~

Why is it binding to 0.0.0.0 instead of localhost / 127.0.0.1 - https://github.com/bitgapp/eqMac/blob/98da95f5dfe5d297464fb4f55843584845446675/native/app/Source/Helpers/Networking.swift#L60 ?

What will be the license of this file: https://github.com/bitgapp/eqMac/blob/ba3d98b2fb73f42539a2cfd582d0d8d137474bbc/native/app/Sandbox.playground/Resources/Mazde%20X%20LissA%20-%20390.mp3 ?
And the same question for this: https://raw.githubusercontent.com/bitgapp/eqMac/ba3d98b2fb73f42539a2cfd582d0d8d137474bbc/native/app/Sandbox.playground/Resources/track.mp3  ?

What's the source of this folder: https://github.com/bitgapp/eqMac/tree/ba3d98b2fb73f42539a2cfd582d0d8d137474bbc/native/driver/Source ?

**Comment by opntr** [comment]
Still waiting for the answers. :)

**Comment by NoahCardoza** [comment]
I'm no expert on this project, but take a look at the [Technology](https://github.com/bitgapp/eqMac#technology) section of the README.

> UI - Web based user interface that is hosted remotely and thus allows for over the air updates & bug fixes. Written in Angular 8 and uses is cached for offline availability.

I couldn't help you with your other questions but I wonder if those audio files are for testing?

I'd just like to take a quick second to thank @nodeful for this awesome solution. Not sure what everyone else is using this for but I for one am using it to allow my to control the volume of my Display Port monitors! Amazing!

**Comment by nodeful** [comment]
@opntr 
It was never my intent to require internet access to use eqMac, besides downloading it initially. Because I'm using a web based user interface I had to rely on some form of hosting of said interface. If the user has internet and eqMac is not blocked from using the internet I will always try to load the latest UI from a remote endpoint, currently https://ui-v1.eqmac.app. This allows me to issue over the air updates to the UI and fix minor bugs without people having to do a native update, which is hard to persuade people to do. In case the internet is not available to eqMac then the app comes shipped with a latest UI source I had a the time for offline hosting. Initially I couldn't make it work by pointing WebView to file://.../index.html file to host it from Application Support directory, so I ended up spawning a small HTTP server on localhost. There were a lot of issues with that, but later I was able to host the files directly from App Support so I got rid of the server. The binding to 0.0.0.0 was only to find available ports on the machine. If you search for the tcpPortIsAvailable or getAvailabilePort references in the code base you will find those functions are not used anywhere at this moment. Thanks for pointing out that I have dangling audio files in the source code I've completely forgot about those, I was using them for testing. Will remove those ASAP.
To answer you last question that source is based of Apple's https://developer.apple.com/library/archive/samplecode/AudioDriverExamples/Introduction/Intro.html example.

**Comment by ddavidebor** [comment]
That’s called a backdoor!

**Comment by nodeful** [comment]
@ddavidebor could you factually explain where do you see a potential for any kind of backdoor?

**Comment by ddavidebor** [comment]
You're running code, updated remotely, without asking the user for
confirmation. Arbitrary remote execution. Since it's baked in
intentionally, it's a backdoor.

**Comment by nodeful** [comment]
The remote code is executed only in the WebView environment within the WebKit sandbox and has no access to any native system capabilities, just like any other website that you are visiting, like GItHub for example. There is no way anyone including myself can do anything malicious without triggering macOS Privacy Permission alert. People can even read the source code and see for themselves. Any other app in existence can do exactly the same even without a Web UI, by downloading remote code and executing it with [JavaScriptCore Framework](https://developer.apple.com/documentation/javascriptcore). 
You should really think before making false claims without doing some easy research and without understanding of the underlying technologies 😃

**Comment by ddavidebor** [comment]
How does your UI communicate with the rest of the app?

**Comment by nodeful** [comment]
@ddavidebor through [WebViewJavascriptBridge](https://github.com/marcuswestin/WebViewJavascriptBridge)
The App has predefined Endpoints/Handlers that follow RESTful architecture. Those are all defined in `...DataBus.swift` classes, like this one: [/native/app/Source/Audio/Effects/Equalizers/Basic/BasicEqualizerDataBus.swift](https://github.com/bitgapp/eqMac/blob/master/native/app/Source/Audio/Effects/Equalizers/Basic/BasicEqualizerDataBus.swift)

**Comment by ddavidebor** [comment]
There you go. Last updated 2017. Try googling "WebViewJavascriptBridge CVE"
or "WebViewJavascriptBridge exploit".

**Comment by nodeful** [comment]
Not sure which exploit do you mean precisely, but I'm guessing the Shazam's fuck up of allowing `shazam://launchurl?url=javascript://...`. If I'm wrong please link the exact CVE of the exploit.
This has nothing to do with eqMac and they way I am handling data comms between the app and UI. 
1. I have no deeplinking in the app currently, I do plan to add it in the future, but I would not allow to execute arbitrary JavaScript code like Shazam allowed.
2. In Shazams case, they allowed users Location to be accessible by the WebView. Not sure why they would do that lol

Basically seems like a mistake by the Shazam's dev team, nothing to do with the underlying tech of the Web to Native bridge.
The particular Bridge implementation hasn't been updated since 2017 but that doesn't mean there are any vulnerabilities because of that lol Apple even allows this Bridge on the AppStore :) 
If you are really scared of apps that use Remote Web UI you should stop using apps like MS Teams, Discord, Slack and every other Electron based app, which there are plenty nowadays.
If you will have any solid evidence of how my implementation is insecure or malicious please let me know I would gladly love to learn implement it in a more secure way! 
I've spent many years in the industry designing and building distributed secure systems and I believe I have a good understanding of IT security, but please prove me wrong :)

**Comment by ddavidebor** [comment]
Uninstalled. If you want to implement your application more securely, move
the web ui so it's fully hosted inside the app, not on your server. This
way the code being executed can be verified.

**Comment by nodeful** [comment]
The code that's being executed can already be verified, by a person that knows where to look.
If you want to stop the UI to be hosted of a remote server then just block eqMac's access to the internet.
I don't care if you uninstall the app or not, honestly 😄 I have thousands of loyal users that understand that I have only good intentions, I don't need negative people like you around.
I'm sorry that you find it hard to understand even the most basic concepts of technology.
Have a good life!

**Comment by nodeful** [comment]
The User that I had the argument related to security of WebView bridge has deleted his comments so I will attach the history of those for reference, otherwise it looks like I was talking to myself:
![IMG_20210315_204019_239.jpg](https://user-images.githubusercontent.com/8472525/111204315-aef54980-85ce-11eb-83f6-6059f398f425.jpg)
![IMG_20210315_204101_975.jpg](https://user-images.githubusercontent.com/8472525/111204420-c3394680-85ce-11eb-855a-1d875a9e620d.jpg)

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by NoahCardoza** [comment]
A little late to the party but I'm glad you posted that screenshot. It did look like you were talking to yourself for a hot second. Totally agree with you though. Makes sense why he'd delete his comments LOL.

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
This has probably been fixed long time ago, I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
