### ISSUE TITLE
MS Teams no audio

### ISSUE THREAD

**Issue by FTT2004** [bitgapp/eqMac#414]
Describe the bug
When running eqMac and Microsoft Teams I am encountering no audio; either receiving or transmitting. I am hearing the beeps when someone joins the meeting and I can hear audio when streaming internet radio.

Steps to Reproduce

eqMac loaded with Login Items
Start MS Teams
Issue occurs

Expected behaviour
Audio to work with eqMac and MS Teams

Setup information:
Audio device used for playback: default
Audio transmission interface: none
macOS Version: MacOS Catalina 10.5.7
eqMac Version: 0.3.6
eqMac UI Version: 1.2.2

Workaround:
Force close eqMac
Restart eqMac
Takes multiple attempts to work

**Comment by rcollette** [comment]
I've been able to workaround this by selecting the output again at the bottom of the window.

**Comment by artdog123** [comment]
> I've been able to workaround this by selecting the output again at the bottom of the window.

I also have this problem but I don't understand what you mean with your workaround. Do you mean reselecting the output in Teams or are you referring something in eqmac?

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
Generally you need to make sure that any conference app is using the "Default Output Device" or eqMac explicitly in the output settings, otherwise eqMac won't receive the audio coming from the app.
I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
