### ISSUE TITLE
Bug: eqMac suddenly has two input devices, one being my system mic

### ISSUE THREAD

**Issue by BenRacicot** [bitgapp/eqMac#415]
I've been using eqMac for about 2 weeks now and it's been fantastic.

However, today I noticed that suddenly my system microphone input was added to the eqMac virtual audio device. Can you help me understand how that happened and how to remove the system mic device from the eqMac device?

<img width="232" alt="Screen Shot 2020-11-20 at 9 47 34 AM" src="https://user-images.githubusercontent.com/1815385/99813251-714b4d00-2b15-11eb-8b7c-d2663a3f65cd.png">

**Comment by nodeful** [comment]
Thanks for being patient with me.
I have just released v1.0.0. You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.0.0
Or from the website: https://eqmac.app
Could you please let me know if this issue is still present. 
Thanks again.

Roman

**Comment by nodeful** [comment]
I'm doing some cleanup of the issues.
eqMac posts two input channels so that people can capture unprocessed system audio with other software.
Since a while ago I don't allow users to select eqMac as the Input device for the system, so this should be fixed. 
I encourage people to try v1.7 by download it from the website: https://eqmac.app
Closing for now, any new issues with eqMac should be submitted through the website.
Thank you!
