### ISSUE TITLE
Keep equalizer status per input

### ISSUE THREAD

**Issue by root-io** [bitgapp/eqMac#553]
I would like to have the "Bass reducer" on a specific input but when I switch to my other inputs to not have it enabled per default. So my feature request would be to persist the activation or not of the equalizer per input.

**Comment by Hickory420** [comment]
I also have a similar request to this (please let me know if I should open a new issue).

When selecting through different inputs, say internal speakers, usb speakers, headphones, it would be nice to have the EQ for that specific input load.

For example, Custom EQ1 for internal speakers, Custom EQ2 for usb speakers, Custom EQ3 for headphones.
When I select an input it would be good if the relevant EQ for the input be loaded as well. Or as mentioned above.

My reasoning for this is, when I listen to music on my USB speakers, I have a Bass driven EQ, but when I am in my zoom meeting, I use my internal speakers and do not require any bass. Last thing I want to do is blow my internal speakers because I forgot to change the EQ (or just turn off the EQ).

Thank you for this awesome app. Truely.

**Comment by erikhuizinga** [comment]
I'd also really like a default eq preset per output device. Is that what you mean by 'input' in the issue title? I usually call my audio devices that produce sound (e.g. MacBook Pro Speakers, External Headphones) outputs, not inputs. Inputs are e.g. microphones. If this issue is about inputs and not outputs, I'll create a new issue, or let me know about other issues that discuss this same subject.

An alternative suggestion, or optionally (as a preference/setting somewhere), eqMac could _remember_ the last selected eq per output device. This is useful, e.g. if I have multiple headphones and multiple eq presets, but on 1 particular day I repeatedly plug in and out 1 specific headphone that I use that day. As a user, I'd like eqMac to switch to my last selected eq on headphone plug in, and to the flat eq (my MacBook Pro Speakers output device preference) every time I pull out the headphone plug. Or when I manually select a different output device in the eqMac UI.

**Comment by mayamaniac** [comment]
Another vote for this feature, to save EQ presets per outputs and auto switch to match depending on the chosen output source. I switch between headphones and my speakers and would like eqMac to switch the preset automatically.

**Comment by posledov** [comment]
+1 vote for this feature!

**Comment by superjeng1** [comment]
This is already possible with the use of "Super Preset" feature! With it, it allows you to make eqMac auto switch eqMac settings when different device is selected. Please do check it out. I am closing this issue since the requested feature has been added, if I missed anything, feel free to reopen this issue.
