### ISSUE TITLE
TV Youtube Bug

### ISSUE THREAD

**Issue by clarityprod** [bitgapp/eqMac#561]
When watching TV Youtube. EqMac is causing youtube TV to pause the video image. It freeze when the audio in the youtube window is in mute. It plays audio fine but pauses the picture playback. Took me a while to figure out that it was eqmac causing the issue. I disabled eqmac and then tv youtube plays as intended. Then I enabled eqmac again ad all is well.  Weird bug but there it is.

**Comment by Pousse** [comment]
I've got the same video freezing issue appearing a few hours after the Mac has started, not only on Youtube, but on EyeTV, VLC, or any video player software. 
I finally found that eqMac v1.3.2 was causing this on my Mac Pro 2013, under Mac OS 10.14.6.
Now, instead of restarting the mac, I quit eqMac and relaunch it.

The issue appears usually at the end of the day, when I'm using multiple video features (playing, exporting, ...) at the same time.

**Comment by superjeng1** [comment]
I have not seen that issue before, I am closing this issue just based on the age of it, if you still encounter this issue, please feel free to reopen it. Note that, there is a pretty long standing bug where if the memory (RAM) usage is too high, macOS's audio output would be inconsistent, and that bug would happen even without eqMac.
