### ISSUE TITLE
eqMac ignores the "Hide App" upon startup setting in System Preferences > Users & Groups > Login Items

### ISSUE THREAD

**Issue by donelson52** [bitgapp/eqMac#565]
eqMac ignores the "Hide App" upon startup setting in System Preferences > Users & Groups > Login Items

The App opens and is visible on the desktop at system startup. The app control window should be hidden upon startup

<img width="650" alt="temp" src="https://user-images.githubusercontent.com/13235881/134147264-ddf6bff9-6ea3-4aca-bfd8-4cb2ef69d84b.png">
.

**Comment by nodeful** [comment]
Apple doesn't let developers to programmatically control the Login Items settings you've shown in the screenshot.
It's recommended to use the "Launch on login" setting in eqMac:
![image](https://user-images.githubusercontent.com/8472525/142540688-688bcb18-c9d8-4ada-b801-8b9ab3b97d32.png)
This bug is not present when using the option from eqMac.
Thank for your report
