### ISSUE TITLE
Bug: Using mic all time in Monteray

### ISSUE THREAD

**Issue by julio-cavallari** [bitgapp/eqMac#582]
**Describe the bug**
Some bluetooth headphones active mono sound when mic is enabled, and after upgrading from Big Sur to Monteray it looks like eqmac is using the mic 100% of the time, and that makes the headphone audio still in mono all the time.

**Expected behaviour**
Keep the microphone disabled to not make the phone go into mono mode

**Setup information:**
 - Audio device used for playback: Mi TW Earphone Lite
 - Audio transmission interface: Bluetooth
 - macOS Version: 12.0.1
 - eqMac Version 1.3.0

**Screenshots or Console.app logs**
![image](https://user-images.githubusercontent.com/53496995/139514320-8719965f-0be3-418f-ac9f-9629dd8b58f2.png)

**Comment by nodeful** [comment]
Yes I've noticed the Notification about the microphone use in Monterey as well.
The reason it's showing that eqMac is using the Microphone is because that's how the eqMac Driver works, it acts like a Virtual Microphone to capture the System Audio. There is another technique to capture the system audio that I'm researching at the moment, so hopefully in the future update I'll be able to avoid using the Virtual Microphone all together. 
The issue with headphones switching to Mono doesn't really relate to this, it's another issue with the way Apple's API get's confused between devices and a lot of developers been complaining to Apple since the dawn of the new API they tell us to use... It doesn't happen to me constantly, maybe 1 out of 100 times I try to use Bluetooth headphones. Does it happen to you all the time? I will try to do more research and mitigate this problem in an upcoming update.
Thanks for your report.

**Comment by julio-cavallari** [comment]
So, as soon as I upgraded to Monterey it was happening almost every time I use a headphone, but it's been 2 days since I've had this problem anymore

**Comment by hexeric** [comment]
EQ explains that it needs access to the IN/OUT system, Monterey changed the information behaviour and now shows with the tedious orange dot that something is using your IN/OUT systems. for met it's only a visual nuisance

**Comment by hexeric** [comment]
i changed to the free 'speakeramp' on appstore for this reason and all is good now

**Comment by nodeful** [comment]
I have managed to achieve a setup where the Microphone is not used at all, I will be making a Pre-release (beta) with a new driver to you guys in a few days once I iron out all the kinks. Thanks for your patience.

**Comment by nodeful** [comment]
I've just release a new PRE-Release v1.4.0 build that should solve this issue.
I'm looking for people to beta test this build.
You can download it here: https://github.com/bitgapp/eqMac/releases/tag/v1.4.0 (eqMac.pkg)
Could you please try it out and report if this issue still persists or if there's any other issues.
Thank you! And sorry for the wait 🙏🏻

**Comment by superjeng1** [comment]
Hi, as this issue is fixed, I would close it now.
