### ISSUE TITLE
Bug: Volume's changing all the time with QC35II connected

### ISSUE THREAD

**Issue by joldwg** [bitgapp/eqMac#583]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
When QC35II are connected, the volume always changes to random percentages and it doesn't let me change it. I then can only make it really loud or really quiet. It's really annoying. Like, the percentages jiggle and then go to the percentage goes to the volume as it was before. I tried EVERYTHING. I've done everything's standing on the website and even reset my Mac. Nothing worked and I'm SO annoyed by this.

**Steps to Reproduce**
I don't know. I just connected my QC35II and the bug was present.

**Expected behaviour**
I just want my volume to function.

**Setup information:**
 - Audio device used for playback: QC35II
 - Audio transmission interface: Bluetooth
 - macOS Version: 12.0.1
 - eqMac Version: 1.3.1
 - eqMac UI Version: 3.0.6

**Screenshots or Console.app logs**
If applicable, add screenshots to help explain your problem. Also you can run Console.app and apply filter for `eqMac` 

**Additional information**
PLEASE FIX ASAP

**Comment by julio-cavallari** [comment]
Same here, the volume stuck in 28% and 69%, even if I try to increase it, if it stays between 28% and 44% it goes back to 28% and if I put it between 69% and 81% it goes back to 69%

**Comment by AbdoulayeTTS** [comment]
Same

**Comment by nodeful** [comment]
Hmm I have QC35II and I don't experience this problem myself.
I will try to replicate this and fix in the next update.
Sorry for the inconvenience 😞

**Comment by julio-cavallari** [comment]
This was happening very often yesterday, I couldn't use the keyboard volume shortcuts, because I needed to put in specific percentages, as described in my last comment, to not turn the volume back, but today it stopped happening, so I don't know if this could be an app issue, or any bugs with the Apple API

**Comment by julio-cavallari** [comment]
https://youtu.be/r95bUJ1B83Q 

i recorded a vídeo to show the bug, i'm sing a Mi TW Earphones Lite

**Comment by adeonir** [comment]
Same here

**Comment by doctordesh** [comment]
I can also verify this bug.

**Comment by nodeful** [comment]
Should be fixed by 9d0cfd25a429f7087e7dbb6e516b54f15ccf50c4
Will be releasing a minor update v1.3.2 with just this fix shortly.
Sorry for the inconvenience everyone, Apple has changed something about their SDK's in Monterey which caused Volume Change events fired 10 times instead of 1 specifically for Bluetooth devices 😕

**Comment by nodeful** [comment]
Hey again, could you please download the pre-release eqMac.pkg v1.3.2 from here: https://github.com/bitgapp/eqMac/releases/tag/v1.3.2
Alternatively you can enable Beta Program in eqMac settings and press "Check for Updates".
And let me know if that fixed the issue for you.
Thank you!

**Comment by nodeful** [comment]
Ok I guess it's mostly fixed, still plenty of work to do with volume handling though, somehow it's the most complex part of the app due to having to override a lot of OS events which macOS doesn't like. Build v1.3.2 is now public and I will be closing this issue, thank you everyone for contributing your time to this!
