### ISSUE TITLE
Can’t Import Presets associated with the Advanced Equalizer

### ISSUE THREAD

**Issue by gij1** [bitgapp/eqMac#600]
I’m running eqMac ver. 1.3.2.  After selecting Advanced Equalizer I clicked on the Gear icon and brought up a Window entitled Advanced Equalizer Settings. I clicked on Import Presets and instead of displaying a list of EQ presets as expected it repeatedly opens the Documents folder from the Finder.

**Comment by superjeng1** [comment]
Hi, this behavior is expected, the Import feature is for importing presets that has been exported using the same window you mentioned. This would be a file that can be easily shared with others if you would like to share your settings. I am closing this issue since this is intended behavior, please reopen this issue if you have other concerns regarding this.
