### ISSUE TITLE
Bug: Weird audio glitches in 1.4.0-1.4.3

### ISSUE THREAD

**Issue by Doridian** [bitgapp/eqMac#618]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
(Yes, I am aware 1.4.x is a beta, but I'd like to see this fixed before a final release)
After a while, some sounds (or all) will start to turn rather weird for a bit.
Weird in this case meaning, it sounds as if the playing sound gets repeated over and over while it continues playing, so it sounds like a really bad echo.
This usually combines with what I'd call "sparkles", like if you had a radio with bad signal or something.
Usually, these go away on their own, but sometimes they cause a permanent audio delay until I disable and re-enable eqMac.
Downgrading to 1.3.x fixes the issue.

I don't know exactly what causes this weirdness, it seems to only happen after at least one sleep/wake cycle and when there is multiple programs producing audio (like YouTube + some notification ding).
My audio pipeline is set to 192 kHz / 24 bit (as that is what my devices support), but I doubt that should be a reason for this.
I tried 48 kHz / 24 bit and get the same results.

I also noticed that sometimes short sound effects, like the Mail ping, can be cut off at the beginning, as if eqMac took a bit to catch onto the fact that sound is now being played (even while I am watching YouTube or listening to Spotify, so it is already playing normal audio, just not effects)

**Steps to Reproduce**
1. Use eqMac for a while
2. Find weird audio glitches

**Expected behaviour**

**Setup information:**
 - Audio device used for playback: Schiit Modius DAC (UAC 2.0)
 - Audio transmission interface: USB -> XLR -> Headphones
 - macOS Version: 12.1
 - eqMac Version 1.4.3

**Screenshots or Console.app logs**
See audio recording of the glitch below. Console.app shows nothing at all useful.

**Additional information**
I have attached an audio recording of the issue. As you can see, in this case YouTube is playing fine, but the Mail ping sound effect is distorted. Sometimes it is the other way around, too (if one notification sound is distorted, usually all of them are, so maybe this has to do with macOS having an "Effects" device and an "Output" device?)
[New Recording.m4a.zip](https://github.com/bitgapp/eqMac/files/7793833/New.Recording.m4a.zip)

In this test, eqMac is enabled and set to "Expert" EQ, but with an entirely flat curve and a global gain of 0.0dB, so it should not change the audio in any way.

**Comment by TBZer0** [comment]
Experiencing something similar. Audio takes a while to "come back" if there was nothing playing for a few minutes. Adjusting the volume seems to jolt it back to working.

**Comment by nodeful** [comment]
Thanks for this report and very concise description!
Yeah there's still a lot of issues with the v1.4 release, more than I expected really. Initially I did the beta release and around a hundred people have migrated to it and didn't report any issues, so I made it live for everyone and when the user base got to a couple thousand I started to get issues reported like you're describing, so I pulled the update from production for now.
Since then the couple weeks over the holidays were a little slow and I'm now getting back into finishing up this update and ironing out all of these bugs.
Regarding eqMac having to catch up to the sound is a double edges sword. On one hand this is needed to minimise CPU usage during period when there's no audio playing, but it takes a split of a second when sound does finally come in to start the Audio processing again unfortunately 😕 Maybe I can optimise it to be quicker at catching up but I can't think of a way right now to make it instant 🤔 Maybe an option in the settings where you don't care about 1-2% CPU usage during silent audio periods for the sake of hearing audio as soon as it's produced?

**Comment by Doridian** [comment]
> 

Personally, I don't mind the cutting in/out too much, but, you could maybe copy the UX of the "Turn off display after" slider in the Battery settings.
As in, make a slider "Turn off eqMac processing if no sound for X time" and the far left is "immediately" and the far right is "never", with some values in between.

**Comment by nodeful** [comment]
I advise to try out this release candidate v1.4.4 and see if it improves your experience:
https://github.com/bitgapp/eqMac/releases/tag/v1.4.4 (eqMac.pkg)

**Comment by Doridian** [comment]
@nodeful So far, seems good. Been running it since you made this response and so far audio has been perfect. Gonna report back later to see if it stayed good, but this is the longest period on 1.4.x that I've not had glitches.

**Comment by Doridian** [comment]
@nodeful Been workling perfectly the past day. Seems all fixed!
Also the crashing (well, the app just becomes unresponsive, even the icon just shows a beachball hovering it and I have to force quit) when unplugging my MacBook from its dock has become more rare, but is not entirely gone (it also did that with 1.3.x, though, so no 1.4 regression)
