### ISSUE TITLE
Bug: Bluetooth is choppy (no matter wether EqMac is running or not)

### ISSUE THREAD

**Issue by gitnik** [bitgapp/eqMac#631]
[x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Bluetooth is extremely choppy after EqMac has been install

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Install EqMac
2. Restart machine
3. Connect to bluetooth speaker
4. Observe extremely choppy audio (whether EqMac is running or not makes no difference)
5. I've tried all the various "Bluetooth" fixes out there, the only thing that works is removing the EqMac driver from `/Library/Audio/Plug-Ins/HAL/`

**Expected behaviour**
Bluetooth sound shouldn't be choppy

**Setup information:**
 - Audio device used for playback: Samsung Galaxy Buds Pro
 - Audio transmission interface: Bluetooth
 - macOS Version: 11.5.1
 - eqMac Version: 1.4.4 (but I've always had this problem, for many months and many EqMac versions)

Happy to provide any further input if needed

**Comment by superjeng1** [comment]
Hi, Is this still happening? I have several models of AirPods and they all work fine. An interesting thing you said is even with eqMac closed, the bug is still happening, but eqMac's driver is disabled when it is not running, so might it is a macOS bug, but I can't really be sure. If this bug still happens to you, please reopen this issue and comment, I would be here to help.
