### ISSUE TITLE
Bug: Can't start the app

### ISSUE THREAD

**Issue by stormborn95** [bitgapp/eqMac#664]
App always went blank like this : 
<img width="446" alt="Screen Shot 2022-04-05 at 10 20 40" src="https://user-images.githubusercontent.com/15722306/161672523-2c29b7c7-9d73-4784-b2e0-45b5e29fa54d.png">
macOS Bigsur 11.6, the only way i can't run eqMac is to use the terminal command.

**Comment by cwarje** [comment]
@stormborn95 Update your mac. It works in macOS Monterey 12.0

**Comment by stormborn95** [comment]
> @stormborn95 Update your mac. It works in macOS Monterey 12.0

Thanks for the help! 
But Monterey have nothing benefit for me to upgrade, i will stay at Bigsur but thanks for the help anyway!

**Comment by superjeng1** [comment]
Hi, this issue is related to #578, your network environment may be blocking eqMac's UI from loading, please turn off any firewall app or switch networks. Once you have the UI showing, and you need to go back to the problematic network, please uncheck the "OTA Updates" box in settings (see the screenshot in the linked issue) I am closing this issue now, please comment on the linked issue if you have anything to add. Thanks!
