### ISSUE TITLE
Earrape when bass boosting

### ISSUE THREAD

**Issue by AwMan3703** [bitgapp/eqMac#692]
M1 MacBook Air here, (I'm not an expert in the audio/music field) - when trying to bass boost, the audio becomes "scratchy" (I don't know the correct term, but like an earrape). The settings aren't a problem, because it was working fine some time ago. Let me know if this is just a "me" problem (and if you know, how to solve it) or there's something wrong with eqMac.
Thank you for your time.

**Comment by Ant137** [comment]
I have this issue too! I'm also using a M1 MacBook Air, but this only happens when I'm using my AirPods. This issue has just started to appear awhile ago.
Hope this helps.

**Comment by nintendork07** [comment]
does this affect your mac when you have a different EQ preset? Or when EQMac is closed?

**Comment by Ant137** [comment]
> does this affect your mac when you have a different EQ preset? Or when EQMac is closed?

This issue also appears in different EQ presets, with the scratchy noise gradually covering more of the audio the higher the bands for the bass is adjusted. The scratchy noise disappears when eqMac is closed. I don't think this is a problem with my AirPods since this has never happened before (until the day the scratchy noise appeared), nor when I'm using a eq app on my android, with them playing audio and a high bass preset being used.

**Comment by 1MaddieX** [comment]
Also been experiencing this issue. Had a bunch of bass-boosted presets that worked just fine until one day this weird distortion started happening at louder volumes. It's almost like the dynamic range or something is being limited and the audio is clipping/distorting at the "edges" of this range? The issue goes away when I turn off eqmac, and I know it's not just my headphones as other eq apps are still working fine on my phone and other devices, wired and over bluetooth.

**Comment by AwMan3703** [comment]
> does this affect your mac when you have a different EQ preset? Or when EQMac is closed?

only when passing the audio through eqmac

**Comment by superjeng1** [comment]
Hi, I assume it is that your EQ Profile could be the problem here. Your EQ profile may have caused the output to go over 0dBFS (normally should be under 0 from minus infinity) if you had positive values set. To solve this issue, check the "Auto" check box next to the Global Gain slider. I think this should solve your issue, so I am going ahead to close it now, if this is not the case, feel free to reopen it and comment on this issue, thanks!

**Comment by AwMan3703** [comment]
Yes, that was the issue. Thanks!
