### ISSUE TITLE
[Question] How to Use Super Preset Feature?

### ISSUE THREAD

**Issue by arandorion** [bitgapp/eqMac#732]
I'm not sure what the **Super Preset** feature is supposed to do, but I can't seem to get it to do anything. Is there any documentation for it?

I get the impression it's supposed to auto-switch when your sound output device changes. I get a notification when that happens, but it doesn't change anything about the app. It doesn't switch to a different EQ profile. What is supposed to be happening?

Thanks

**Comment by nodeful** [comment]
I knew this would come up at some point as I agree the User Experience is not the most straight forward with this feature.
You know how when you have an EQ preset selected and you made a change the presets switches to Manual and you have to save the preset again if you want those settings to apply to a preset.
With Super Presets the behaviour is a little different. If you have a Super Preset selected and you make any changes it is instantly saved to the selected preset. So what probably happened in your case is that you created a preset for 1 setup, then instantly started to create a setup for the 2nd preset, but this whole time you were applying the new settings to the 1st preset.
What you need to do once you created the first preset is press the "Deselect" button or create a new preset straight away. Only then start applying the settings that you want for the 2nd preset. 
I hope this explains the behaviour, if you have a suggestion on how I can make this better, please let me know, I'm open to discuss and modify this feature.

**Comment by grorliofo** [comment]
Hi, I do have the same "issue".
I do understand your explanation of order. But I dont manage to get it happen.
The Super preset doesnt change after automatic device switch. Once in a while it does including the banner that it changed. But the behavior appears to be erratic an incomprehensible to me. Is there a more detailed step by step explanation of how to get it working, or is there perhaps a bug involved? Thanks for pointing out, as I think this is a brilliant feature I would love to use!

**Comment by JarrettBillingsley** [comment]
I don't know if I'm doing something wrong with this feature. I have two Super Presets with different EQs, one for the internal speakers and one for a headset. I can manually switch between them fine, and they definitely have different EQs. I have them both set up to auto-switch based on which output device is used. eqMac detects which output device is being used, but it does not auto-switch the super presets. I also have "Notify when Autoswitched" turned on for both presets and I never get a notification, so it doesn't seem to be triggering the preset autoswitching at all.

**Comment by grorliofo** [comment]
Hi everyone with this issue.
Now it seems to be working reliably for me. Not sure what changed. What I found out is:
When you have the EqMac Panel open, the shown Superuserpreset will always be active. So if you change/plug anoterh device it will not change to the desired preset as the current one will rule over. So if I set things the way I want and close the panel EqMac does switch properly including the notification of the change.
Specs: Version 1.7.2 driver: 2.3.1 UI: 4.4.1 MacM1max Monterey 12.5
Maybe that helps...

**Comment by JarrettBillingsley** [comment]
It still does not work for me even if I have the eqMac panel closed. I have the exact same versions of everything eqMac related, but I am on Monterey 12.1 on a 2015 Air. Maybe there is an OS compatibility issue.

**Comment by grorliofo** [comment]
Very strange. It works for me with three different devices: Headphones, Macspeakers, external device. Only thing coming to my mind is that the battery might have fully drained over the holidays leading to a reset of the NVRAM/SMC. MAybe this resetted a driver, which made things working. Far fetched, but only thing coming to my mind.
But anyways I realize, that although it magically started working on my machine with the automatic switching of devices and presets triggered by plugging/unplugging: the fact that the apparent preset in the open panel always seems to have priority, it means that manual switching of the output device via the EqMac panel itself will always bypass the switching of the superpreset, or even mess up the assigments of superpreset with the output devices.

**Comment by grorliofo** [comment]
Update: now it seems to work all the way it is supposed to. 
It changes the designated presets and eqs according to automatic (plugging devices) as well as manual (selscting via EqMac panel) changing of devices...
It is totally unclear and utterly erratic to me as there have been no updates on any component...
Only thing I observed while the testing is, that eqMac will never change presets until there is audio being put out. So if you test and try keep always an audio stream running. At least this could perhaps resolve some confusion.
Otherwise it seems the best I can do is wishing everyone luck..

**Comment by seb-koch** [comment]
I hope this is the right place to ask as it relates to the Super Preset: Is there any plan to save the Balance configuration in the preset? In my scenario I am having different balance setup depending on the output device.

Thanks for the great work, so far I very much like eqMac.

**Comment by superjeng1** [comment]
Hi, let me try to clarify this. A "Super Preset" contains all (almost, except the volume) the settings on the UI. When a "Super Preset" is selected, it would restore all (almost) settings in the app. While you make changes to anything in the app, the changes is immediately saved to the currently active "Super Preset". You could choose to activate a "Super Preset" automatically when a output device is active or a certain app is output-ing. The switching logic happens when any audio starts to play.

**Comment by 7enChan** [comment]
I tried to set up the Super Preset function, but it doesn't automatically switch settings when switching devices. Instead, it only switches automatically when I open the Main Audio app in my settings. I don't know if this is how the function works or if there is a bug on my computer causing this.

**Comment by grorliofo** [comment]
I dont know why, but since a few days it is not working as it did before anymore. It just stopped switching super presets. Its strange, as it worked finde before and I didnt update any component.
Any ideas? would be great to have it working again!

**Comment by MKatwood** [comment]
Adding on that I have the same problem as many previous people mentioned where swapping the output device does not auto-switch to the correct Super Preset despite appearing to be set up correctly.
Here are my Super Preset settings:
<img width="340" alt="Screenshot 2024-01-10 at 11 31 16 AM" src="https://github.com/bitgapp/eqMac/assets/22086412/af8e71dc-7333-4506-b23a-7fa9662cf342"><img width="340" alt="Screenshot 2024-01-10 at 11 31 03 AM" src="https://github.com/bitgapp/eqMac/assets/22086412/75e5ec8b-ba9e-4f5b-a6c2-191e87463ebf">

With those settings applied and no headphones plugged in, the main interface appears like this (dropdown menu at bottom auto-selects MacBook Pro Speakers)
<img width="446" alt="Screenshot 2024-01-10 at 11 32 33 AM" src="https://github.com/bitgapp/eqMac/assets/22086412/6e133db4-d805-4edb-afd1-2f7b7a7c0403">
when I have the headphones plugged in it looks like this (bottom drop-down menu auto switches to External Headphones but Super Preset does not change)
<img width="446" alt="Screenshot 2024-01-10 at 11 32 22 AM" src="https://github.com/bitgapp/eqMac/assets/22086412/68c3a200-6f21-4109-90b7-159ea1ed0f75">

**Comment by TheKayThatWasOrange** [comment]
I can confirm that this feature does absolutely nothing when an output device changes.

**Comment by luismrguimaraes** [comment]
Same here. Only seems to work if I disable and reenable the "Super Preset" feature, i.e. clicking this button twice
<img width="73" alt="image" src="https://github.com/bitgapp/eqMac/assets/100025288/2339db61-8bad-45b6-900f-44c4cb230920">

**Comment by TheKayThatWasOrange** [comment]
It's abandonware. Documenting all the ways it is broken is probably not a wise use of anyone's time.

**Comment by grorliofo** [comment]
I havent tried the whole procedure by rweir, but I can tell it is working for me reliably since a while. See my other comments above if helpful. I think its worth to check this thread as it will get things done for you. Ignore someones unconstructive comments. For a freeware it is quite powerful. Thanks to the developer, though hopefully these bugs will get tracked down and lift things to an intuitive level.

**Comment by matthewlipski** [comment]
+1 to @rweir's comment - super profiles and auto-switching seem to be working for me but the UI isn't updating accordingly.

I have 2 super profiles setup, "Headphones", which uses an EQ preset for my headphones, and "Speakers", which uses a flat EQ preset. I have these set to automatically switch when eqMac switches between the "External Speakers" and "MacBook Pro Speakers" outputs.

When I plug/unplug headphones to/from the audio jack, the audio output automatically switches and I see the super profile in eqMac change accordingly, so the Super Profiles panel and auto-switching works fine. I can also hear that the EQ profiles are working properly for both profiles.

However, despite this, the Equalizers panel doesn't change, and this is also true for the Output panel dropdown which still shows the old output and old active devices. Interestingly, after clicking the cog button in the Output panel, the menu which opens up actually does show the correct active devices unlike the dropdown.

Right clicking the UI and clicking the "Reload" option forces the UI to update, and after doing that both the Equalizers and Output tabs display the correct settings for the active super profile.

So really it seems like everything is working properly in the background, it's just parts of the UI aren't updating automatically  and I have to use the "Reload" option to fix that. Not sure if this behavior is what everyone in this thread is experiencing, but it definitely seems to line up with @rweir's findings.

Really like eqMac and will continue to support it, though I hope this issue can get resolved soon!

**Comment by dan-iway** [comment]
I have one more "Gotcha" to add to the list!
I have a "Default" preset that has "Automatic Switching" active but no output device selected and a second "Output X" preset. It worked as expected; change the output to X it switches to the "Output X" preset, switch to any other output it switches back to "Default".

But i could not get the same behaviour for any new presets I added. Turns out I did not realize **the Super Preset list is orderable**!  The newly added presets were added at the end and therefore switching outputs never reached them and ended up at the "Default" one. After moving "Default" to the end of the list now it works as expected.
Makes sense in hindsight, my impression just was that eqMac intelligently selected the "Default" only when no other, more specific one matches - but that is not the case, it just follows the order in the list.

**Comment by mikhail-fedosenko** [comment]
Wow, the last comment of @dan-iway was very helpful to me - i was trying to figure out why the preset is not deselected, when it's no longer matching the condition (isn't it a bug? or the intended way of working?). So, i ended up of creating a "nothing/default" super preset linked with outputs not needed the superpreset.
But the hint that putting this superpreset as the last one + not linking with any output will make it "last resort"/fallback superpreset. Thanks a lot :)
