### ISSUE TITLE
Bug: input microphone audio level very low

### ISSUE THREAD

**Issue by jaredmcqueen** [bitgapp/eqMac#741]
this is a continuation of https://github.com/bitgapp/eqMac/issues/121

When eqMac is running, the microphone level is barely audible.  I cannot answer calls on my macbook, nor use my voice in meetings like Slack, Webex, Zoom, etc. because the microphone audio is so low.  I have quit eqMac for the audio to be usable.

**Comment by nuxcodes** [comment]
This. My Mac is almost useless for FaceTime when eqmac is on. Had to manually quit the app every time which gets frustrating

**Comment by dasti555** [comment]
You don't need to quit the app just "disable" it in the upper left corner. But yes I just noticed this and it's so bad oh. 
I'm on Ventura not sure about others.

**Comment by Zayul** [comment]
I am also experiencing this issue. Microphone is useless in Facetime while eqMac is enabled.

**Comment by nodeful** [comment]
Ok so I don't use an iPhone and hence never came across this issue while developing the app.
Today I borrowed and iPhone and was testing this functionality for like 6 hours and can confirm that this is an issue and needs to be solved.
Unfortunately Apple does some black magic fuckery with audio device in the background, like creating hidden aggregate device and does a bunch of voice processing stuff in the background. For some reason when combined with eqMacs driver it's also "ducking" the Microphone volume together with other audio, which is totally not how it's supposed to work :\
I've tried a bunch of stuff and couldn't find a solution for now. 
I'm about to release a new update and thinking to just disable eqMac while there's an active call.
I will file an Apple Feedback request and see how they respond.
As a workaround for now, you can select the Output Device in Facetime > Video menu that you're using, instead of the eqMac device:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/8472525/208002813-7f340332-0a0e-4bba-8392-d3529b2c9523.png">

This will return the Mic volume back to normal

**Comment by superjeng1** [comment]
Hi, this is a long standing issue and we are working to find a workaround. I would close this issue since there is a issue that is pretty close to this one. Please track the progress over there, thanks! #605

**Comment by philipJmauch** [comment]
Is there either a fix or a workaround for this? I can't renew my subscription in a few months if I have to choose between being able to use FaceTime and being able to EQ the rest of my Mac. I also need this app to control the volume of my external monitor using my keyboard, so I can't not have that every time that I need to use FaceTime.
