### ISSUE TITLE
Bug: Airpod Pro Gen 2 (audio selection issue) Macbook Pro Intel

### ISSUE THREAD

**Issue by TheLostTinyTurtle** [bitgapp/eqMac#748]
The Airpod Pro Gen 2 connect correctly but there is no audio when connected to Mac EQ. Solved when disconnecting MacEQ. Tried to switch audio in system settings, and it is recognizing MacQE pairing and headphones, but not sound. Tried it on multiple browsers (FF, Chrome, and Safari) along with music player.

**Comment by dasti555** [comment]
What OS?

**Comment by TheLostTinyTurtle** [comment]
> What OS?

Monterey, 12.6

**Comment by dasti555** [comment]
> > What OS?
> 
> Monterey, 12.6

I think the issue will be somehow connected with that as the new generation of AirPods needs Ventura and Ventura will be released later this year. Or perhaps apple makes them fully functional with older OS. (I doubt). Because for example when you are low batter on case Monterey shows that your airpods need replace battery (because OS thinks its airtag basically)

**Comment by TheLostTinyTurtle** [comment]
I was originally on Big Sur which did not recognize them at all. I upgraded
to Monterey and they work flawlessly other than connecting to eqMac and
being able to use virtual headsets. I also tried with Krisp AI virtual
headsets and they seemed to not connect to it either. I imagine it is a
problem that will be fixed with Ventura. Granted I'll need to wait until
13.2v before I would upgrade.

**Comment by superjeng1** [comment]
Hi, I think this might be fixed in the latest version of eqMac. But it's true that there are still some flakiness around AirPods in general with eqMac. I am closing this issue now but if you are still having this issue please reply/comment/reopen this issue so we can have a look at it.
