### ISSUE TITLE
Bug: EqMac went wrong when using LosslessSwitcher

### ISSUE THREAD

**Issue by darranmoore** [bitgapp/eqMac#752]
**Describe the bug**
When running EqMac with Apple Music (hi-res lossless) using LosslessSwitcher app, after changes of track that invoke a change of bit-rate that requires LS to switch bit-rate EqMac outputs error in audio. It sounds like out of pitch/slowed down

**Steps to Reproduce**
Steps to reproduce the behaviour (feel free to change the placeholder as you need):
1. Whilst running EqMac and LosslessSwitcher play hi-res Apple Music
2. After change in track to track with different bit-rate error is audible3. 
3. Reseting audio normally corrects error or restart EqMac app

**Expected behaviour**
Audio output sounds slow/pitch shift

**Setup information:**
 - Audio device used for playback: Chord Mojo
 - Audio transmission interface: USB-C
 - macOS Version: 12.5.1
 - eqMac Version: v1.6.2
 - eqMac UI Version N/A

**Screenshots or Console.app logs**
?

**Additional information**
N/A

**Comment by pattont** [comment]
Describe the bug
I am seeing the above bug in Apple Music as well anytime the output format changes the sound coming through is horrific. It's glitchy, slow, full of terrible sounds. 

I am also seeing this same issue with Qobuz which changes the output format automatically. If I start a track through eqMac of one format, then find a different track that is a different resolution this same bug pops up. This doesn't just happen through the mojo2 this happens when I just select my laptop speakers.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/2903357/211708567-dadb4599-440f-4b29-996e-857490702d03.png">

If I change my source to Mojo2 or my Macbook speakers (thus skipping eqMac) this problem disappears. There is something going on when the output format is changed from one song to the next that eqMac does not like.

Any help would be greatly appreciated. I am also happy to test any beta versions to help identify the bug. I just bought a lifetime eqMac license so I will help any way I can to get this resolved.  

Steps to Reproduce
Open Qobuz playing a song in one resolution with the eqMac output selected. Then, change songs to a high-res song and the bug will typically appear after just that single switch. I was able to reproduce it on just my macbook speakers skipping my mojo2.

In Apple Music you need LossLessSwitcher which you can snag from google. In Apple Music you need to have Lossless Audio enabled and then start the LosslessSwitcher which changes the output format in the "Audio Midi Setup" in MacOS automatically per song. 

More Information on LosslessSwitcher:
https://darko.audio/2022/04/losslessswitcher-adds-bit-perfect-apple-music-playback-to-macos/

Setup information:

Audio device used for playback: Chord Mojo 2
Audio transmission interface: USB-C
Macbook Pro 16" M1 Max
macOS Version: 13.1
eqMac Version: v1.7.2
eqMac UI Version N/A
Screenshots or Console.app logs
?

Additional information
I am happy to do a screenshare if you want to set up a time to show you the process to reproduce.

**Comment by nodeful** [comment]
Hey there, thank you for the detailed report!
This issue was one of my main focuses on the latest update that I just released to Beta testers:
https://github.com/bitgapp/eqMac/releases/tag/v1.7.4

Can you try out this release and let me know if the issue with Sample Rate switching performs well now :)

**Comment by superjeng1** [comment]
Hi, this is now fixed in the newer versions of eqMac, so I am closing this issue right now. Please reply/comment on this if you still have any issue relating to this.
