### ISSUE TITLE
Bug: System sound gone after machine sits for extended time

### ISSUE THREAD

**Issue by bbarnes870** [bitgapp/eqMac#755]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
Usually after leaving machine overnight the program needs to be quit and restarted to pass sound.

**Steps to Reproduce**
Leave machine overnight or extended time without use.

**Expected behaviour**
Machine does not produce sound on web, music, or quicktime.

**Setup information:**
 - Audio device used for playback: Universal Audio Volt 276
 - Audio transmission interface: USB 
 - macOS Version: Ventura 13.0
 - eqMac Version [e.g. 0.0.1]1.6.2
 - eqMac UI Version [e.g. 0.0.4] 4.3.1

**Additional information**
M1 Mac Mini 2020 16GB RAM, 1TB SSD

**Comment by faryar76** [comment]
i have same issue

**Comment by superjeng1** [comment]
Hi, as it is really hard to replicate this issue, could you confirm that if this is still happening on the latest version of eqMac please?

**Comment by schalkneethling** [comment]
@bbarnes870, @faryar76, @superjeng1 - This might be related to https://github.com/bitgapp/eqMac/issues/780 - I experience both of these issues on macOS Venture with an Apple M2 chip.

**Comment by superjeng1** [comment]
@schalkneethling Thanks! It does sound similar but it's a bit different. #780 happens when eqMac doesn't see it's driver, but the driver is actually there, it is just the system has not fully woke up. If this is driver related, it might be the shared memory of the app and the driver went out of sync and could only be fixed currently by restarting `coreaudiod`. 
As I have not heard back from @bbarnes870 or @faryar76 yet, I would close this issue for now. If you are still having this issue, please feel free to comment on this.
