### ISSUE TITLE
Bug?: Timeout occurs and sound stops.

### ISSUE THREAD

**Issue by sokz5** [bitgapp/eqMac#798]
**Disclaimer:** 
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
It is not clear which specific procedure causes this, but as shown in the video, a timeout occurs and no sound is produced.

https://user-images.githubusercontent.com/30361510/215531005-17437bca-fe04-47f0-b3f6-d052f020a723.mp4

**Steps to Reproduce**
unclear

I noticed that there is no sound, checked the ecmac and once I turn it off as shown in the video, it plays normally.
Also, once I enable the ecmac, it plays once, but I get a red Timed out message and no sound again.

**Setup information:**
 - Audio device used for playback: Built-in mac speaker
 - macOS Version: 13.1（22C65）
 - eqMac Version: 1.7.2 (use pro)

**Comment by Fidgital** [comment]
I am having the same issue, which only started for me today.

Audio device used for playback: External Headphones
MacOS Version: 11.6.1
eqMac Version: 1.7.2

**Comment by sokz5** [comment]
Still not resolved in this version
App: v1.7.4
Driver: v2.4.0
UI v4.4.9 (Local)

**Comment by superjeng1** [comment]
This happens when the app lost communication with the driver. The easiest way to solve this is to restart `coreaudiod` which is macOS's audio process with this command. This happens sometimes and it is not really clear as on how to solve it yet.
`sudo launchctl kickstart -k system/com.apple.audio.coreaudiod`
