### ISSUE TITLE
Bug: Audio driver has to be reinstalled every day

### ISSUE THREAD

**Issue by mustevenplay** [bitgapp/eqMac#827]
**Disclaimer:** 
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.
- [x] I have checked for a similar issue and sure it hasn't been reported before.

**Describe the bug**
The pop-up informing that the audio driver needs to be installed (again), randomly appears.
It's most likely a bug, since there hasn't been updates since I'm getting the problem.

**Steps to Reproduce**
1. Open Eqmac, and occasionally, you'll get the pop-up.

**Expected behaviour**
That not appearing every time.

**Setup information:**
 - Audio device used for playback: Any
 - Audio transmission interface: Any
 - macOS Version: 13.2.1
 - eqMac Version 1.7.10
 - eqMac UI Version 4.6.3

**Screenshots or Console.app logs**
<img width="446" alt="Screenshot 2023-03-14 at 14 11 21" src="https://user-images.githubusercontent.com/14057832/225013253-80ad1c15-d80b-4496-b4e2-505e2207a762.png">

**Comment by RonvD** [comment]
Yes same issue here. And eqMac stop working after there is no sound in my browser, FireFox after a couple of minutes. I see that headphone icon in my systemtray where normally that speaker icon is where you can change the volume.

**Comment by jacobweberbowery** [comment]
Happening here too. MacOS 13.3, M1 MacBook Pro, eqMac 1.7.10.

**Comment by jbeck22** [comment]
Same here...very annoying!

MacOS 13.2
M1 MacBook Air
eqMac v1.7.10
driver v2.4.3

**Comment by tcz305** [comment]
i also still have this bug

**Comment by norvele** [comment]
I am having the same bug. It may have something to do with macOS, because I had the same thing when I was using Boom

MacBook Air 2020 M1
MacOS 13.2.1 (22D68)
eqMac v1.7.10

**Comment by spoco2** [comment]
Same issue

Apple M2 Pro 2023
macOS 13.3.1 (22E261)
eqMac v1.7.10

**Comment by isommers1** [comment]
Still happening basically every time I wake from sleep. Version 1.7.10, driver v2.4.3. 
MacBook Pro M1 Pro 
macOS 13.3.1(a).

**Comment by humanafterallwav** [comment]
I was struggling with this issue too, and for as crazy as it might sound i might have solved it just setting the app in window mode instead of popover mode (the green circular button on top left). I'm not saying it 100% works but i can tell that since i did it a week and a half ago i havent had the app asking me to install the drivers, as soon as i switched again to popover mode it lasted one day and then i got asked to install the drivers. Now I'm back to window mode and haven't had any request in the last 3 days.
Maybe you can try and give a feedback to understand if it's just been shear luck or if it actually does something.
Really hope to help, this bug is so annoying...

**Comment by flintpnz** [comment]
Same issue

Version 1.7.10, driver v2.4.3
MacBook Pro M1 Pro
macOS 13.4

**Comment by superjeng1** [comment]
Duplicate to #780.
