### ISSUE TITLE
Auto switch audio device

### ISSUE THREAD

**Issue by albyddr** [bitgapp/eqMac#830]
Hi, is there a way to not have the output of an audio device automatically selected as soon as it is replaced?

Like I select "AirPods Pro" and he changed to the equalized version "AirPods Pro eqMac"

Thanks

**Comment by superjeng1** [comment]
Hi, this is necessary because this is how we capture audio. We currently need to set the system output to our virtual device to get the audio for processing. We plan to change this in the future, and not require a virtual device. But this would take a long time, since there is a lot of code that has to be rewritten. I would close this issue for now, but feel free to comment on any thing related to this.
