### ISSUE TITLE
Bug: Eq mac forcing chrome to use the mic

### ISSUE THREAD

**Issue by UnknownCrafts** [bitgapp/eqMac#934]
Disclaimer:
Please go through [existing issues](https://github.com/bitgapp/eqMac/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22) to avoid creating duplicates. If you found a similar issue please post a comment there. If you are uncertain your issue is related to others then create the issue. Obvious ignorance of this rule might get you blocked from posting new issues. Please tick the box below to show that you have followed the guideline.

 I have checked for a similar issue and sure it hasn't been reported before.
Describe the bug

EQ Mac seems to force google chrome to activate the mic? ~~Also I am not too sure if its cuz of the dev beta~~ (Still occurs on public beta)

Steps to Reproduce
Use eqmac and play any video on youtube or any other website with audio.

Expected behaviour

The mic should not have to be activated

Setup information:

Audio device used for playback: Sony XM4
Audio transmission interface: Bluetooth
macOS Version: 15 Dev Beta 4
eqMac Version 1.8.8
eqMac UI Version 5.1.3 (Remote)
eqMac driver version 2.5.4

Video:

I have attached a video. Just incase quick time isn't able to open the video, I would suggest using vlc player because I used ffmpeg to shrink the video size a bit so that I could upload it to github. 

https://github.com/bitgapp/eqMac/assets/65975222/f4d4346a-00e2-48ff-915b-61e70ea7768e

**Comment by UnknownCrafts** [comment]
Update: The issue still persists in macos dev beta 3

**Comment by nsvrana** [comment]
I have the same issue with Zoom.

**Comment by UnknownCrafts** [comment]
Update: Still persists on MacOS Public Beta 1

**Comment by ragauskl** [comment]
@UnknownCrafts Can you confirm that issue does not occur when eqMac is not running and you switch between various outputs? I have Sonoma 14.3 and when in youtube toggling eqMac bypass on and off I can see the microphone 'blink' sometimes as on>off quickly or remain on but not always, however if I quit eqMac and switch between Macbook Air Speakers and BlackHole device the microphone also sometimes appears indicating it may be a chrome issue and not eqMac

**Comment by UnknownCrafts** [comment]
> @UnknownCrafts Can you confirm that issue does not occur when eqMac is not running and you switch between various outputs? I have Sonoma 14.3 and when in youtube toggling eqMac bypass on and off I can see the microphone 'blink' sometimes as on>off quickly or remain on but not always, however if I quit eqMac and switch between Macbook Air Speakers and BlackHole device the microphone also sometimes appears indicating it may be a chrome issue and not eqMac

Yep, the issue does not occur when switching between my headphones and Mac speakers. Sometimes when I quickly turn eqmac on, off and then on again, the indicator does not show up. Also, one time FreeTube(an open-source YouTube player) asked me for the microphone permission(which I denied) when I had eqmac enabled even though that had never happened with eqmac off. This could be a macOS issue with the way it handles audio drivers since you did mention that even blackhole is triggering the microphone. Also adding on to the FreeTube situation, AFAIK, the app does not need the microphone permission as there is no voice typing feature or anything like that, so my guess is that eqmac somehow forced FreeTube to access the microphone(or maybe made it so macOS thinks that FreeTube is the one accessing the microphone?) which doesn't make sense from a macOS app security point of view.

**Comment by ragauskl** [comment]
I confirmed with dev that eqMac should not be causing this because currently it doesn't in any way use microphone (also doesn't have permissions for it) or need other apps to use it, there's nothing coded in it to do so (there used to be but it was removed a while back, it will also be added in future with certain features, but right now there's nothing). It could however as you mention be the way macOS (or chromium because freetube is made with Electron and I don't see the microphone flicker with non-chromium apps like QuickLook - but today I also barely see it with Chrome as well so not sure) handles virtual audio drivers and their different types. This could likely be out of scope for eqMac as it's not using or forcing a microphone use, maybe there's some workaround that can be done to avoid this, but that could also have it's side effects.

We can't reliably replicate this tho, only see some microphone flicker sometimes, so if dev will get this issue somehow consistently he may look into debugging it and providing a workaround/solution, but until then this will unlikely be investigated further as core issue is likely not in eqMac itself

**Comment by naanoo** [comment]
I have the same problem. It is reproducible and exactly as shown in the video by @UnknownCrafts 

Warm regards from Germany.

**Comment by ragauskl** [comment]
The fix is now pending to be released with stable release of 1.8.8. If anyone will see this after 1.8.8 is in stable release - let me know

**Comment by naanoo** [comment]
@ragauskl Merci! I will give you feedback when it is released.

**Comment by scriptpony** [comment]
@ragauskl any word on when that stable release will go live? This bug makes it annoying to watch movies/content because the orange dot (mic in use) icon remains on screen. Thanks!

**Comment by ragauskl** [comment]
It was decided to release existing 1.8.8 as semi-stable (the update from app will still not show it, but if you download from the website it will be 1.8.8). This is because the more important fix which also fixes the microphone was moved over to v1.8.9, but as it affect a lot of functionality it will be first released in beta. Hopefully in upcoming week or so, as soon as some other issues get resolved. The release of 1.8.9 to stable will depend on user feedback

**Comment by BanjoCam** [comment]
I am still experiencing this issue on 1.8.8. 
<img width="244" alt="image" src="https://github.com/user-attachments/assets/a7f56e8a-5baa-41e7-a337-cefb9f0f51c8">
<img width="326" alt="image" src="https://github.com/user-attachments/assets/acac3cf9-6990-4c29-b6a2-0ac0279dcab0">
Orange microphone disappears as soon as I toggle the eqMac bypass.

Thank you

**Comment by Noire86** [comment]
> I am still experiencing this issue on 1.8.8. 
> 
> <img width="244" alt="image" src="https://github.com/user-attachments/assets/a7f56e8a-5baa-41e7-a337-cefb9f0f51c8">
> 
> <img width="326" alt="image" src="https://github.com/user-attachments/assets/acac3cf9-6990-4c29-b6a2-0ac0279dcab0">
> 
> Orange microphone disappears as soon as I toggle the eqMac bypass.
> 
> 
> 
> Thank you

I am experiencing the same issue on the same version of eqmac, sadly

**Comment by ragauskl** [comment]
@BanjoCam @Noire86 As mentioned above - "because the more important fix which also fixes the microphone was moved over to v1.8.9" which is still being worked on/finalised

**Comment by 0xAdriaTorralba** [comment]
Is there anywhere where we can download and test the beta for v1.8.9? :)

**Comment by ragauskl** [comment]
@0xAdriaTorralba It's not out yet but will be soon, make sure to enable 'Beta Program' to be able to update to it once it's out

**Comment by ragauskl** [comment]
1.8.9 now available in beta, please do keep in mind that it's beta and it includes major underlaying changes to the driver, developer fixed any issues he could replicate (including this one), but that does not mean that new issues will not occur to others or that all issues are definitely fixed. Any feedback is valuable so that we can know if it's working as expected to everyone and what issues are still present

**Comment by scriptpony** [comment]
Works great for me so far @ragauskl ! Awesome work to the team!

**Comment by ErrorProne** [comment]
Works for me 👍  thanks

**Comment by UnknownCrafts** [comment]
Just got to try out the new beta and it's working smoothly! Thank you! No more "mic is being used" dots. 😄
